### ISSUE TITLE
Unrecoverable crash when using vanilla hopper to input enchanted armor into washing machine

### ISSUE THREAD

**Issue by the-ible** [MrCrayfish/MrCrayfishFurnitureMod#1]
MrCrayfishFurnitureMod v3.4.7
Forge Mod Loader version 7.10.85.1291
Java Version: 1.7.0_67

I was getting enchanted armor from mod grinder and fish traps. So i was in need of a auto repair armor to prep armor for striping of enchants. So we had MrCrayfish Furniture Mod washing machine running, the issue started right after i put a mincraft Hopper on top and put some armor inside of the hopper. 

1. Can you reproduce this bug with just the hopper and putting armor in? No!!
Hopper with gold helm = OK
Hopper with gold helm going in to chest = OK
Hopper on washing machine = ok -untill you put the armor in to the hopper, then crash.

2. Or does the hopper need to be connected to the washing machine to produce the bug? 
Yes

3. Exactly what kind of armor are you using to reproduce the bug? 
Gold helm i reproduce twice. Also crash if i put in chain mail chest armor.

Other thoughts is that if the hopper connects to inventory and just drops it in, but the washing machine does have four slots with a peace of gear having to match that slot, meaning if the hopper is forcing the gear in to another slot that it is not suppose to go in maybe that the issue?

---- Minecraft Crash Report ----
// My bad.

Time: 2/20/15 2:43 PM
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
at net.minecraft.tileentity.TileEntityHopper.func_152102_a(TileEntityHopper.java:312)
at net.minecraft.tileentity.TileEntityHopper.func_145883_k(TileEntityHopper.java:277)
at net.minecraft.tileentity.TileEntityHopper.func_145887_i(TileEntityHopper.java:205)
at net.minecraft.tileentity.TileEntityHopper.func_145845_h(TileEntityHopper.java:190)
at net.minecraft.world.World.func_72939_s(World.java:1939)
at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
at net.minecraft.tileentity.TileEntityHopper.func_152102_a(TileEntityHopper.java:312)
at net.minecraft.tileentity.TileEntityHopper.func_145883_k(TileEntityHopper.java:277)
at net.minecraft.tileentity.TileEntityHopper.func_145887_i(TileEntityHopper.java:205)
at net.minecraft.tileentity.TileEntityHopper.func_145845_h(TileEntityHopper.java:190)

-- Block entity being ticked --
Details:
Name: Hopper // net.minecraft.tileentity.TileEntityHopper
Block type: ID #154 (tile.hopper // net.minecraft.block.BlockHopper)
Block data value: 0 / 0x0 / 0b0000
Block location: World: (-196,64,-1423), Chunk: (at 12,4,1 in -13,-89; contains blocks -208,0,-1424 to -193,255,-1409), Region: (-1,-3; contains chunks -32,-96 to -1,-65, blocks -512,0,-1536 to -1,255,-1025)
Actual block type: ID #154 (tile.hopper // net.minecraft.block.BlockHopper)
Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
at net.minecraft.world.World.func_72939_s(World.java:1939)
at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)

-- Affected level --
Details:
Level name: New World
All players: 1 total; [EntityPlayerMP['poqkakashi'/11315, l='New World', x=-193.77, y=63.00, z=-1421.82]]
Chunk stats: ServerChunkCache: 1252 Drop: 0
Level seed: -7663906559181702482
Level generator: ID 00 - default, ver 1. Features enabled: true
Level generator options: 
Level spawn location: World: (136,64,228), Chunk: (at 8,4,4 in 8,14; contains blocks 128,0,224 to 143,255,239), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
Level time: 130169 game time, 164499 day time
Level dimension: 0
Level storage version: 0x04ABD - Anvil
Level weather: Rain time: 82998 (now: false), thunder time: 5736 (now: false)
Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: true
Stacktrace:
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

-- System Details --
Details:
Minecraft Version: 1.7.10
Operating System: Windows 7 (amd64) version 6.1
Java Version: 1.7.0_67, Oracle Corporation
Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
Memory: 1050212072 bytes (1001 MB) / 2151309312 bytes (2051 MB) up to 5298978816 bytes (5053 MB)

**Comment by MrCrayfish** [comment]
Thanks for the report.

**Comment by MrCrayfish** [comment]
This is fixed now :)

**Comment by synthetic65535** [comment]
nope. https://github.com/MrCrayfish/MrCrayfishFurnitureMod/issues/34#issuecomment-321345584
