### ISSUE TITLE
crashes when shift-clicking an item into the inventory for a piece of furniture (btw, the toaster doesn't seem to work for me)

### ISSUE THREAD

**Issue by scigeotech** [MrCrayfish/MrCrayfishFurnitureMod#122]
crash report:

>---- Minecraft Crash Report ----
// Ouch. That hurt :(

Time: 1/11/17 4:27 PM
Description: Updating screen events

java.lang.NullPointerException: The validated object is null
	at org.apache.commons.lang3.Validate.notNull(Validate.java:222)
	at org.apache.commons.lang3.Validate.notNull(Validate.java:203)
	at net.minecraft.util.NonNullList.set(SourceFile:45)
	at net.minecraft.entity.player.InventoryPlayer.func_70299_a(InventoryPlayer.java:513)
	at net.minecraft.inventory.Slot.func_75215_d(Slot.java:70)
	at com.mrcrayfish.furniture.gui.containers.ContainerEski.func_82846_b(ContainerEski.java:93)
	at net.minecraft.inventory.Container.func_184996_a(Container.java:237)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187098_a(PlayerControllerMP.java:550)
	at net.minecraft.client.gui.inventory.GuiContainer.func_184098_a(GuiContainer.java:632)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73864_a(GuiContainer.java:391)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:542)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:510)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1695)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1056)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:372)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at org.apache.commons.lang3.Validate.notNull(Validate.java:222)
	at org.apache.commons.lang3.Validate.notNull(Validate.java:203)
	at net.minecraft.util.NonNullList.set(SourceFile:45)
	at net.minecraft.entity.player.InventoryPlayer.func_70299_a(InventoryPlayer.java:513)
	at net.minecraft.inventory.Slot.func_75215_d(Slot.java:70)
	at com.mrcrayfish.furniture.gui.containers.ContainerEski.func_82846_b(ContainerEski.java:93)
	at net.minecraft.inventory.Container.func_184996_a(Container.java:237)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187098_a(PlayerControllerMP.java:550)
	at net.minecraft.client.gui.inventory.GuiContainer.func_184098_a(GuiContainer.java:632)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73864_a(GuiContainer.java:391)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:542)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:510)

-- Affected screen --
Details:
	Screen name: com.mrcrayfish.furniture.gui.GuiEski

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['ItSureStingz'/246, l='MpServer', x=-53.85, y=103.00, z=239.28]]
	Chunk stats: MultiplayerChunkCache: 225, 225
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (40,64,227), Chunk: (at 8,4,3 in 2,14; contains blocks 32,0,224 to 47,255,239), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 2939742 game time, 49711 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 49 total; [EntityZombie['Zombie'/128, l='MpServer', x=-37.50, y=28.00, z=278.50], EntityZombie['Zombie'/129, l='MpServer', x=-32.50, y=28.00, z=272.50], EntityCreeper['Creeper'/130, l='MpServer', x=-34.06, y=26.00, z=279.46], EntitySkeleton['Skeleton'/131, l='MpServer', x=-33.50, y=25.00, z=308.50], EntitySheep['Sheep'/134, l='MpServer', x=-19.67, y=71.00, z=171.76], EntityPlayerSP['ItSureStingz'/246, l='MpServer', x=-53.85, y=103.00, z=239.28], EntityCreeper['Creeper'/135, l='MpServer', x=-31.50, y=25.00, z=276.50], EntityCreeper['Creeper'/136, l='MpServer', x=-18.30, y=44.00, z=315.60], EntityBat['Bat'/143, l='MpServer', x=-11.57, y=36.58, z=159.57], EntitySkeleton['Skeleton'/144, l='MpServer', x=-2.50, y=16.00, z=245.50], EntitySkeleton['Skeleton'/145, l='MpServer', x=-15.30, y=44.00, z=313.49], EntityCreeper['Creeper'/146, l='MpServer', x=-16.00, y=44.00, z=313.47], EntityCreeper['Creeper'/147, l='MpServer', x=-14.50, y=55.00, z=315.50], EntityCreeper['Creeper'/150, l='MpServer', x=13.50, y=44.00, z=317.50], EntityChicken['Chicken'/40, l='MpServer', x=-129.82, y=84.00, z=231.12], EntityChicken['Chicken'/41, l='MpServer', x=-131.00, y=83.00, z=231.58], EntityCreeper['Creeper'/44, l='MpServer', x=-128.17, y=39.00, z=292.50], EntityPig['Pig'/47, l='MpServer', x=-124.67, y=93.00, z=177.50], EntityChicken['Chicken'/48, l='MpServer', x=-127.35, y=85.00, z=238.19], EntitySkeleton['Skeleton'/51, l='MpServer', x=-122.50, y=52.00, z=250.50], EntitySquid['Squid'/52, l='MpServer', x=-113.24, y=49.67, z=256.34], EntitySkeleton['Skeleton'/53, l='MpServer', x=-119.50, y=23.00, z=283.50], EntityZombie['Zombie'/58, l='MpServer', x=-100.28, y=12.00, z=237.54], EntitySquid['Squid'/59, l='MpServer', x=-109.69, y=49.45, z=252.48], EntitySquid['Squid'/60, l='MpServer', x=-107.40, y=48.00, z=259.60], EntitySquid['Squid'/61, l='MpServer', x=-107.40, y=49.24, z=258.87], EntityBat['Bat'/62, l='MpServer', x=-111.25, y=37.00, z=289.96], EntityVillager['Villager'/73, l='MpServer', x=-88.74, y=77.56, z=234.90], EntityVillager['Villager'/74, l='MpServer', x=-88.26, y=78.00, z=235.71], EntityVillager['Villager'/75, l='MpServer', x=-88.30, y=77.00, z=234.28], EntityItem['item.item.rottenFlesh'/76, l='MpServer', x=-93.32, y=77.00, z=235.88], EntityChicken['Chicken'/96, l='MpServer', x=-66.50, y=76.31, z=238.50], EntityChicken['Chicken'/97, l='MpServer', x=-66.80, y=75.00, z=239.80], EntityChicken['Chicken'/98, l='MpServer', x=-66.80, y=75.00, z=239.80], EntityVillager['Villager'/99, l='MpServer', x=-65.70, y=77.00, z=239.07], EntityItem['item.item.egg'/100, l='MpServer', x=-66.88, y=75.00, z=239.88], EntityItem['item.item.egg'/107, l='MpServer', x=-63.76, y=75.00, z=214.70], EntityChicken['Chicken'/108, l='MpServer', x=-58.85, y=75.00, z=210.81], EntityChicken['Chicken'/109, l='MpServer', x=-55.50, y=74.00, z=239.12], EntityZombie['Zombie'/110, l='MpServer', x=-59.69, y=28.00, z=248.43], EntityZombie['Zombie'/111, l='MpServer', x=-62.50, y=28.00, z=245.50], EntityZombie['Zombie'/112, l='MpServer', x=-60.50, y=28.00, z=247.50], EntityZombie['Zombie'/113, l='MpServer', x=-62.50, y=28.00, z=247.50], EntityPig['Pig'/114, l='MpServer', x=-61.72, y=88.00, z=271.50], EntityPig['Pig'/115, l='MpServer', x=-56.53, y=94.02, z=255.36], EntityEnderman['Enderman'/116, l='MpServer', x=-57.50, y=38.00, z=308.50], EntityCreeper['Creeper'/124, l='MpServer', x=-38.50, y=29.00, z=170.50], EntitySkeleton['Skeleton'/125, l='MpServer', x=-33.50, y=33.00, z=160.50], EntityCow['Cow'/127, l='MpServer', x=-47.50, y=78.00, z=260.80]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:415)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2655)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:393)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.11.2
	Operating System: Windows 10 (x86) version 10.0
	Java Version: 1.8.0_111, Oracle Corporation
	Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
	Memory: 88820504 bytes (84 MB) / 523501568 bytes (499 MB) up to 523501568 bytes (499 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx512M -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 1, tcache: 1, allocated: 12, tallocated: 94
	FML: MCP 9.38 Powered by Forge 13.20.0.2206 5 mods loaded, 5 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	minecraft{1.11.2} [Minecraft] (minecraft.jar) 
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.11.2-13.20.0.2206.jar) 
	UCHIJAAAA	forge{13.20.0.2206} [Minecraft Forge] (forge-1.11.2-13.20.0.2206.jar) 
	UCHIJAAAA	cfm{4.1.1} [MrCrayfish's Furniture Mod] (cfm-4.1.1-mc1.11.2.jar) 
	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'Intel' Version: '4.3.0 - Build 20.19.15.4531' Renderer: 'Intel(R) HD Graphics 4400'
	Launched Version: 1.11.2-forge1.11.2-13.20.0.2206
	LWJGL: 2.9.4
	OpenGL: Intel(R) HD Graphics 4400 GL version 4.3.0 - Build 20.19.15.4531, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i3-4030U CPU @ 1.90GHz

**Comment by sudo-apt-get-install** [comment]
Please use Pastebin next time

**Comment by MrCrayfish** [comment]
Fixed in 1.12.2
