### ISSUE TITLE
Crashes in Multiplayer server only when inventory opens- single player fine.

### ISSUE THREAD

**Issue by DaddyP1G** [MrCrayfish/MrCrayfishFurnitureMod#213]
The game crashed whilst unexpected error
Error: java.lang.IllegalArgumentException: Attempted to get the ID for a unknown recipe: net.minecraft.item.crafting.ShapelessRecipes@4de042ec Name: cfm:white_fence

---- Minecraft Crash Report ----

WARNING: coremods are present:
Contact their authors BEFORE contacting forge

// Oops.

Time: 3/26/18 4:21 PM
Description: Unexpected error

java.lang.IllegalArgumentException: Attempted to get the ID for a unknown recipe: net.minecraft.item.crafting.ShapelessRecipes@d7c7c22 Name: cfm:white_fence
	at net.minecraft.stats.RecipeBook.func_194075_d(RecipeBook.java:53)
	at net.minecraft.stats.RecipeBook.func_193830_f(RecipeBook.java:35)
	at net.minecraft.client.gui.recipebook.RecipeList.func_194210_a(SourceFile:34)
	at net.minecraft.client.gui.recipebook.GuiRecipeBook.lambda$updateCollections$0(GuiRecipeBook.java:161)
	at net.minecraft.client.gui.recipebook.GuiRecipeBook$$Lambda$302/1919840712.accept(Unknown Source)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at net.minecraft.client.gui.recipebook.GuiRecipeBook.func_193003_g(GuiRecipeBook.java:159)
	at net.minecraft.client.gui.recipebook.GuiRecipeBook.func_193014_a(GuiRecipeBook.java:96)
	at net.minecraft.client.gui.recipebook.GuiRecipeBook.func_194303_a(GuiRecipeBook.java:73)
	at net.minecraft.client.gui.inventory.GuiInventory.func_73866_w_(SourceFile:52)
	at net.minecraft.client.gui.GuiScreen.func_146280_a(GuiScreen.java:478)
	at net.minecraft.client.Minecraft.func_147108_a(Minecraft.java:1016)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2173)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:2018)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1806)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1096)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.stats.RecipeBook.func_194075_d(RecipeBook.java:53)
	at net.minecraft.stats.RecipeBook.func_193830_f(RecipeBook.java:35)
	at net.minecraft.client.gui.recipebook.RecipeList.func_194210_a(SourceFile:34)
	at net.minecraft.client.gui.recipebook.GuiRecipeBook.lambda$updateCollections$0(GuiRecipeBook.java:161)
	at net.minecraft.client.gui.recipebook.GuiRecipeBook$$Lambda$302/1919840712.accept(Unknown Source)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at net.minecraft.client.gui.recipebook.GuiRecipeBook.func_193003_g(GuiRecipeBook.java:159)
	at net.minecraft.client.gui.recipebook.GuiRecipeBook.func_193014_a(GuiRecipeBook.java:96)
	at net.minecraft.client.gui.recipebook.GuiRecipeBook.func_194303_a(GuiRecipeBook.java:73)
	at net.minecraft.client.gui.inventory.GuiInventory.func_73866_w_(SourceFile:52)
	at net.minecraft.client.gui.GuiScreen.func_146280_a(GuiScreen.java:478)
	at net.minecraft.client.Minecraft.func_147108_a(Minecraft.java:1016)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2173)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:2018)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Daddy_P1G'/1405, l='MpServer', x=3.99, y=62.94, z=230.86]]
	Chunk stats: MultiplayerChunkCache: 169, 169
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-64,64,248), Chunk: (at 0,4,8 in -4,15; contains blocks -64,0,240 to -49,255,255), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 32740346 game time, 32937254 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: true), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 109 total; [EntityVillagerMCA['Carissa'/256, l='MpServer', x=-9.50, y=66.94, z=240.70], EntitySheep['Sheep'/270, l='MpServer', x=9.71, y=66.00, z=155.52], EntityPig['Pig'/271, l='MpServer', x=13.69, y=66.00, z=170.17], EntitySheep['Sheep'/272, l='MpServer', x=13.68, y=66.00, z=172.21], EntitySheep['Sheep'/273, l='MpServer', x=7.77, y=64.00, z=189.15], EntityVillagerMCA['Frances'/274, l='MpServer', x=0.45, y=63.00, z=221.45], EntityVillagerMCA['Saul'/275, l='MpServer', x=0.42, y=64.00, z=209.97], EntityVillagerMCA['Chan'/277, l='MpServer', x=-0.17, y=63.00, z=213.52], EntityVillagerMCA['Wallace'/278, l='MpServer', x=0.78, y=63.00, z=218.51], EntityVillagerMCA['Woodrow'/279, l='MpServer', x=-5.55, y=63.00, z=216.68], EntityVillagerMCA['Coriander'/280, l='MpServer', x=6.75, y=63.00, z=225.47], EntityVillagerMCA['Gayle'/281, l='MpServer', x=19.02, y=63.00, z=226.96], EntityVillagerMCA['Regine'/282, l='MpServer', x=8.03, y=63.00, z=221.50], EntityVillagerMCA['Hyman'/283, l='MpServer', x=-0.58, y=64.00, z=237.70], EntityVillagerMCA['Narcissus'/284, l='MpServer', x=26.00, y=65.00, z=248.00], EntityItem['item.item.egg'/1053, l='MpServer', x=22.50, y=63.00, z=229.06], EntityVillagerMCA['March'/285, l='MpServer', x=22.28, y=65.00, z=245.57], EntityVillagerMCA['Amparo'/286, l='MpServer', x=24.73, y=65.00, z=248.00], EntityVillagerMCA['Mitchel'/287, l='MpServer', x=18.85, y=63.00, z=227.88], EntityVillagerMCA['Lois'/288, l='MpServer', x=-3.27, y=64.00, z=236.90], EntityVillagerMCA['Donnie'/289, l='MpServer', x=-1.26, y=64.00, z=237.62], EntityVillagerMCA['Blair'/290, l='MpServer', x=21.69, y=64.00, z=242.49], EntityVillagerMCA['Christi'/291, l='MpServer', x=-8.00, y=69.00, z=250.00], EntityVillagerMCA['Jene'/292, l='MpServer', x=24.30, y=65.00, z=248.94], EntityVillagerMCA['Walton'/293, l='MpServer', x=-1.30, y=64.00, z=236.81], EntityVillagerMCA['Ben'/295, l='MpServer', x=-0.46, y=70.00, z=252.27], EntityVillagerMCA['Jesse'/296, l='MpServer', x=-3.52, y=65.00, z=252.69], EntityVillagerMCA['Rosie'/297, l='MpServer', x=33.50, y=64.00, z=234.66], EntityVillagerMCA['Laurene'/298, l='MpServer', x=0.45, y=65.00, z=278.81], EntityVillagerMCA['Bernadette'/299, l='MpServer', x=8.50, y=65.00, z=278.22], EntityItem['item.item.egg'/1071, l='MpServer', x=23.36, y=63.00, z=228.23], EntityItem['item.item.egg'/1077, l='MpServer', x=23.21, y=63.00, z=225.40], EntityChicken['Chicken'/319, l='MpServer', x=27.17, y=64.00, z=206.50], EntitySheep['Sheep'/320, l='MpServer', x=17.50, y=63.00, z=220.55], EntitySheep['Sheep'/321, l='MpServer', x=23.55, y=63.00, z=213.45], EntitySheep['Sheep'/322, l='MpServer', x=18.19, y=63.00, z=214.35], EntitySheep['Sheep'/323, l='MpServer', x=17.45, y=63.00, z=213.45], EntitySheep['Sheep'/324, l='MpServer', x=23.23, y=63.00, z=222.50], EntityChicken['Chicken'/326, l='MpServer', x=22.95, y=63.00, z=228.15], EntityChicken['Chicken'/327, l='MpServer', x=23.19, y=63.00, z=228.65], EntityChicken['Chicken'/328, l='MpServer', x=23.80, y=63.00, z=225.18], EntityChicken['Chicken'/329, l='MpServer', x=22.32, y=63.00, z=225.59], EntityChicken['Chicken'/330, l='MpServer', x=23.35, y=63.00, z=224.86], EntityChicken['Chicken'/331, l='MpServer', x=23.08, y=63.00, z=224.39], EntityChicken['Chicken'/332, l='MpServer', x=22.43, y=63.00, z=225.05], EntityPig['Pig'/333, l='MpServer', x=18.50, y=63.00, z=235.91], EntityPig['Pig'/335, l='MpServer', x=17.45, y=63.00, z=236.69], EntityCow['Cow'/336, l='MpServer', x=23.55, y=63.00, z=235.45], EntityCow['Cow'/338, l='MpServer', x=23.16, y=63.00, z=238.41], EntityPig['Pig'/340, l='MpServer', x=20.35, y=63.00, z=236.26], EntityPig['Pig'/342, l='MpServer', x=19.73, y=63.00, z=237.40], EntityCow['Cow'/343, l='MpServer', x=17.45, y=63.00, z=235.45], EntityVillagerMCA['Kathyrn'/344, l='MpServer', x=4.50, y=68.00, z=243.29], EntityPlayerSP['Daddy_P1G'/1405, l='MpServer', x=3.99, y=62.94, z=230.86], EntitySheep['Sheep'/359, l='MpServer', x=44.57, y=66.00, z=187.19], EntityCow['Cow'/360, l='MpServer', x=45.82, y=65.00, z=210.28], EntitySheep['Sheep'/361, l='MpServer', x=46.18, y=67.00, z=203.67], EntitySheep['Sheep'/370, l='MpServer', x=60.75, y=64.00, z=152.50], EntitySheep['Sheep'/372, l='MpServer', x=61.85, y=68.00, z=165.28], EntitySheep['Sheep'/373, l='MpServer', x=58.63, y=68.00, z=165.20], EntitySheep['Sheep'/374, l='MpServer', x=60.51, y=68.00, z=166.73], EntityPig['Pig'/375, l='MpServer', x=55.92, y=64.00, z=185.31], EntityPig['Pig'/376, l='MpServer', x=61.63, y=66.00, z=181.79], EntitySheep['Sheep'/377, l='MpServer', x=62.48, y=66.00, z=178.77], EntitySheep['Sheep'/378, l='MpServer', x=61.30, y=70.00, z=214.46], EntitySheep['Sheep'/379, l='MpServer', x=62.27, y=70.00, z=227.50], EntityItem['item.item.egg'/1404, l='MpServer', x=22.32, y=63.00, z=226.01], EntityCreeper['Creeper'/1407, l='MpServer', x=80.50, y=59.00, z=291.50], EntityBat['Bat'/397, l='MpServer', x=57.08, y=11.02, z=160.00], EntitySheep['Sheep'/1427, l='MpServer', x=77.49, y=71.00, z=250.73], EntitySkeleton['Skeleton'/1428, l='MpServer', x=73.86, y=59.00, z=286.64], EntityZombie['Zombie'/1437, l='MpServer', x=82.50, y=54.00, z=234.50], EntityBat['Bat'/1457, l='MpServer', x=74.78, y=15.10, z=154.25], EntityBat['Bat'/1459, l='MpServer', x=74.46, y=18.97, z=159.90], EntityCreeper['Creeper'/1466, l='MpServer', x=80.18, y=41.00, z=255.50], EntitySheep['Sheep'/1472, l='MpServer', x=80.03, y=68.00, z=274.63], EntityRabbit['Rabbit'/195, l='MpServer', x=-71.66, y=64.00, z=165.01], EntitySkeleton['Skeleton'/1481, l='MpServer', x=81.25, y=49.00, z=216.50], EntitySheep['Sheep'/203, l='MpServer', x=-52.51, y=65.00, z=190.20], EntitySheep['Sheep'/204, l='MpServer', x=-52.73, y=65.00, z=200.45], EntitySheep['Sheep'/205, l='MpServer', x=-56.08, y=65.00, z=201.12], EntitySheep['Sheep'/1485, l='MpServer', x=76.48, y=65.00, z=232.23], EntityCreeper['Creeper'/1488, l='MpServer', x=65.50, y=23.00, z=170.50], EntityCreeper['Creeper'/1489, l='MpServer', x=71.98, y=21.00, z=168.50], EntitySkeleton['Skeleton'/1490, l='MpServer', x=65.50, y=23.00, z=171.50], EntityBat['Bat'/1491, l='MpServer', x=77.51, y=19.40, z=169.23], EntitySkeleton['Skeleton'/1492, l='MpServer', x=76.50, y=19.00, z=170.50], EntityCreeper['Creeper'/1493, l='MpServer', x=72.50, y=19.00, z=168.83], EntityCreeper['Creeper'/1494, l='MpServer', x=73.50, y=19.00, z=170.50], EntityBat['Bat'/1495, l='MpServer', x=66.83, y=27.14, z=169.24], EntitySkeleton['Skeleton'/1496, l='MpServer', x=69.54, y=46.00, z=169.76], EntitySheep['Sheep'/220, l='MpServer', x=-47.71, y=64.00, z=176.48], EntityCreeper['Creeper'/1500, l='MpServer', x=81.50, y=16.00, z=189.50], EntityCreeper['Creeper'/1501, l='MpServer', x=81.50, y=16.00, z=188.50], EntityVillagerMCA['Clarice'/231, l='MpServer', x=-4.50, y=69.00, z=242.35], EntityVillagerMCA['Lan'/232, l='MpServer', x=-20.48, y=68.00, z=248.51], EntityVillagerMCA['Young'/233, l='MpServer', x=-20.45, y=69.00, z=241.93], EntityVillagerMCA['Kacey'/243, l='MpServer', x=-0.37, y=63.00, z=211.30], EntityVillagerMCA['Madelene'/244, l='MpServer', x=-0.40, y=63.00, z=212.66], EntityVillagerMCA['Blanca'/245, l='MpServer', x=8.99, y=63.00, z=221.50], EntityVillagerMCA['Clay'/247, l='MpServer', x=-5.66, y=64.00, z=233.30], EntityIronGolem['Iron Golem'/248, l='MpServer', x=-1.70, y=64.00, z=233.70], EntityVillagerMCA['Nickolas'/249, l='MpServer', x=-19.50, y=69.00, z=239.50], EntityVillagerMCA['Lise'/250, l='MpServer', x=-20.54, y=68.00, z=249.43], EntityVillagerMCA['Marianna'/251, l='MpServer', x=-17.22, y=67.00, z=252.55], EntityIronGolem['Iron Golem'/252, l='MpServer', x=-5.86, y=66.94, z=244.00], EntityIronGolem['Iron Golem'/253, l='MpServer', x=-2.93, y=64.00, z=235.23], EntityVillagerMCA['Jocelyn'/254, l='MpServer', x=-14.76, y=69.00, z=240.48], EntityVillagerMCA['Wilbert'/255, l='MpServer', x=-14.30, y=69.56, z=241.70]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:532)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2748)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:426)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 970280088 bytes (925 MB) / 1556086784 bytes (1484 MB) up to 2863661056 bytes (2731 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3072m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.42 Powered by Forge 14.23.2.2624 Optifine OptiFine_1.12.2_HD_U_D1 12 mods loaded, 12 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State       | ID         | Version      | Source                               | Signature                                |
	|:----------- |:---------- |:------------ |:------------------------------------ |:---------------------------------------- |
	| UCHIJAAAAAA | minecraft  | 1.12.2       | minecraft.jar                        | None                                     |
	| UCHIJAAAAAA | mcp        | 9.42         | minecraft.jar                        | None                                     |
	| UCHIJAAAAAA | FML        | 8.0.99.99    | forge-1.12.2-14.23.2.2624.jar        | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAAAA | forge      | 14.23.2.2624 | forge-1.12.2-14.23.2.2624.jar        | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAAAA | cfm        | 4.2.0        | furniture-4.2.0-1.12.2.jar           | None                                     |
	| UCHIJAAAAAA | jei        | 4.8.0.111    | jei_1.12.2-4.8.0.111.jar             | None                                     |
	| UCHIJAAAAAA | journeymap | 1.12.2-5.5.2 | JourneyMap-Mod-1.12.2-Unlimited.jar  | None                                     |
	| UCHIJAAAAAA | radixcore  | 1.12.x-2.2.1 | RadixCore-1.12.x-2.2.1-universal.jar | None                                     |
	| UCHIJAAAAAA | mca        | 1.12.2-5.3.1 | MCA-1.12.x-5.3.1-universal.jar       | None                                     |
	| UCHIJAAAAAA | corerm     | 1.3.0        | RikMuldsCore_1.3.0.jar               | None                                     |
	| UCHIJAAAAAA | camping    | 2.4.0        | TheCampingMod_2.4.0.jar              | None                                     |
	| UCHIJAAAAAA | wit        | 1.0.25       | WIT-1.12.jar                         | None                                     |

	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13492 Compatibility Profile Context 22.19.677.257' Renderer: 'AMD Radeon R9 200 Series'
	Launched Version: forge-14.23.2.2624
	LWJGL: 2.9.4
	OpenGL: AMD Radeon R9 200 Series GL version 4.5.13492 Compatibility Profile Context 22.19.677.257, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 16x AMD Ryzen 7 1700X Eight-Core Processor 
	OptiFine Version: OptiFine_1.12.2_HD_U_D1
	OptiFine Build: 20180323-135452
	Render Distance Chunks: 9
	Mipmaps: 3
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: KUDA-Shaders v6.1 Legacy.zip
	OpenGlVersion: 4.5.13492 Compatibility Profile Context 22.19.677.257
	OpenGlRenderer: AMD Radeon R9 200 Series
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 16

**Comment by DaddyP1G** [comment]
Looks like it only happens while in creative
