### ISSUE TITLE
Server crash when mob touches electric fence

### ISSUE THREAD

**Issue by 0xicl33n** [MrCrayfish/MrCrayfishFurnitureMod#222]
**Modpack:** FTB Revelation 1.8 custom (added cfm and thats it)
**Version:** cfm-4.2.0-mc1.12.2.jar

```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  CTMCorePlugin (CTM-MC1.12-0.2.3.12.jar)
  BedPatch (bedpatch-2.2-1.12.2.jar)
  AstralCore (astralsorcery-1.12.2-1.8.5.jar)
  LoadingPlugin (Quark-r1.4-123.jar)
  Plugin (NotEnoughIDs-1.5.4.2.jar)
  CoreMod (Aroma1997Core-1.12.2-1.3.0.2.jar)
  MalisisCorePlugin (malisiscore-1.12.2-6.4.0.jar)
  ShetiPhian-ASM (shetiphiancore-1.12.0-3.5.6.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  FMLPlugin (elulib-0.1.12.jar)
  ComfortsCoreLoadingPlugin (comforts-1.12.2-1.1.0.2.jar)
  ForgelinPlugin (Forgelin-1.6.0.jar)
  Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.9.5-1.12.2-anarchy.jar)
  LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
  AdvancedRocketryPlugin (AdvancedRocketry-1.12.2-1.4.0-67.jar)
  TransformerLoader (OpenComputers-MC1.12.2-1.7.2.67.jar)
  SecretRoomsMod-Core (secretroomsmod-1.12.2-5.5.5.jar)
  IELoadingPlugin (ImmersiveEngineering-0.12-80-core.jar)
Contact their authors BEFORE contacting forge

// Ouch. That hurt :(

Time: 4/27/18 2:03 AM
Description: Colliding entity with block

java.lang.IllegalArgumentException: Cannot get property PropertyBool{name=full_block, clazz=class java.lang.Boolean, values=[true, false]} as it does not exist in BlockStateContainer{block=cfm:electric_fence, properties=[east, north, south, west]}
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177229_b(BlockStateContainer.java:201)
	at mod.chiselsandbits.chiseledblock.BlockChiseled.func_149662_c(BlockChiseled.java:361)
	at com.mrcrayfish.furniture.blocks.BlockElectricFence.sparkle(BlockElectricFence.java:218)
	at com.mrcrayfish.furniture.blocks.BlockElectricFence.func_180634_a(BlockElectricFence.java:177)
	at net.minecraft.entity.Entity.func_145775_I(Entity.java:1042)
	at net.minecraft.entity.Entity.func_70091_d(Entity.java:963)
	at net.minecraft.entity.EntityLivingBase.func_191986_a(EntityLivingBase.java:1949)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2384)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:577)
	at net.minecraft.entity.monster.EntityMob.func_70636_d(EntityMob.java:45)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2170)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295)
	at net.minecraft.entity.monster.EntityMob.func_70071_h_(EntityMob.java:50)
	at net.minecraft.entity.monster.EntitySpider.func_70071_h_(SourceFile:87)
	at net.minecraft.world.World.func_72866_a(World.java:1990)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1952)
	at net.minecraft.world.World.func_72939_s(World.java:1756)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:765)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Thread.java:748)
```

Full crash report: https://hastebin.com/mehopepemu.sql

This seems to be inconsistent, sometimes it crashes and sometimes it doesnt. It also does not seem to crash in singleplayer and seems to only happen in servers.

**Comment by MrCrayfish** [comment]
Closing since I won't be maintaining 1.12.2 anymore.
