### ISSUE TITLE
forge server crash

### ISSUE THREAD

**Issue by kest874** [MrCrayfish/MrCrayfishFurnitureMod#23]
I use a forge server on my local lan to play with my kids.  With the latest dev version I get the following crash:

Description: Exception in server tick loop

net.minecraftforge.fml.common.LoaderException: java.lang.NoClassDefFoundError: com/mrcrayfish/furniture/entity/EntityMirror
	at net.minecraftforge.fml.common.LoadController.transition(LoadController.java:162)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:693)
	at net.minecraftforge.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:97)
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:360)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:210)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:438)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NoClassDefFoundError: com/mrcrayfish/furniture/entity/EntityMirror
	at com.mrcrayfish.furniture.MrCrayfishFurnitureMod.init(MrCrayfishFurnitureMod.java:131)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:518)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:208)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:187)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:692)
	... 5 more
Caused by: java.lang.ClassNotFoundException: com.mrcrayfish.furniture.entity.EntityMirror
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 33 more
Caused by: net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerException: Exception in class transformer net.minecraftforge.fml.common.asm.transformers.SideTransformer@20435c40 from coremod FMLCorePlugin
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:234)
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
	... 35 more
Caused by: java.lang.RuntimeException: Attempted to load class com/mrcrayfish/furniture/entity/EntityMirror for invalid side SERVER
	at net.minecraftforge.fml.common.asm.transformers.SideTransformer.transform(SideTransformer.java:49)
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:230)
	... 37 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.8
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_60, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 789141392 bytes (752 MB) / 925892608 bytes (883 MB) up to 3797417984 bytes (3621 MB)
	JVM Flags: 0 total; 
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.10 FML v8.0.37.1334 Minecraft Forge 11.14.1.1334 4 mods loaded, 4 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized
	FML{8.0.37.1334} [Forge Mod Loader] (forge-1.8-11.14.1.1334-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized
	Forge{11.14.1.1334} [Minecraft Forge] (forge-1.8-11.14.1.1334-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized
	cfm{3.5} [§9MrCrayfish's Furniture Mod] (MrCrayfishFurnitureModv3.5-dev(1.8)1.jar) Unloaded->Constructed->Pre-initialized->Errored
	Loaded coremods (and transformers): 
	Profiler Position: N/A (disabled)
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by kest874** [comment]
Latest commits resolve this.

**Comment by kest874** [comment]
Failed to realize I need to compile it to get it to work, when will you release the next build?

**Comment by ikurhai** [comment]
Hellow !

Still have that error with v3.5-dev version.


>---- Minecraft Crash Report ----
>// Ouch. That hurt :(
>
>Time: 03/11/15 20:16
>Description: Exception in server tick loop
>
>net.minecraftforge.fml.common.LoaderException: java.lang.NoClassDefFoundError: com/mrcrayfish/furniture/entity/EntityMirror
>	at net.minecraftforge.fml.common.LoadController.transition(LoadController.java:163)
>	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:733)
>	at net.minecraftforge.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:97)
>	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:360)
>	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:210)
>	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:438)
>	at java.lang.Thread.run(Thread.java:701)
>Caused by: java.lang.NoClassDefFoundError: com/mrcrayfish/furniture/entity/EntityMirror
>	at com.mrcrayfish.furniture.MrCrayfishFurnitureMod.init(MrCrayfishFurnitureMod.java:131)
>	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
>	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>	at java.lang.reflect.Method.invoke(Method.java:622)
>	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:537)
>	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
>	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>	at java.lang.reflect.Method.invoke(Method.java:622)
>	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
>	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
>	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
>	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
>	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
>	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
>	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
>	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
>	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>	at java.lang.reflect.Method.invoke(Method.java:622)
>	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
>	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
>	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
>	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
>	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
>	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
>	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:731)
>	... 5 more
>Caused by: java.lang.ClassNotFoundException: com.mrcrayfish.furniture.entity.EntityMirror
>	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
>	at java.lang.ClassLoader.loadClass(ClassLoader.java:323)
>	at java.lang.ClassLoader.loadClass(ClassLoader.java:268)
>	... 33 more
>Caused by: net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerException: Exception in class transformer net.minecraftforge.fml.common.asm.transformers.SideTransformer@59e0b2fa from coremod FMLCorePlugin
>	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:234)
>	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
>	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
>	... 35 more
>Caused by: java.lang.RuntimeException: Attempted to load class com/mrcrayfish/furniture/entity/EntityMirror for invalid side SERVER
>	at net.minecraftforge.fml.common.asm.transformers.SideTransformer.transform(SideTransformer.java:49)
>	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:230)
>	... 37 more
>
>A detailed walkthrough of the error, its code path and all known details is as follows:
>---------------------------------------------------------------------------------------
>
>-- System Details --
>Details:
>	Minecraft Version: 1.8
>	Operating System: Linux (amd64) version 3.2.0-4-amd64
>	Java Version: 1.6.0_36, Sun Microsystems Inc.
>	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Sun Microsystems Inc.
>	Memory: 1351088096 bytes (1288 MB) / 1544814592 bytes (1473 MB) up to 1544814592 bytes (1473 MB)
>	JVM Flags: 2 total; -Xmx1524M -Xms1524M
>	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
>	FML: MCP v9.10 FML v8.0.99.99 Minecraft Forge 11.14.3.1543 4 mods loaded, 4 mods active
>	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
>	UCHI    mcp{9.05} [Minecraft Coder Pack] (minecraft.jar)
>	UCHI    FML{8.0.99.99} [Forge Mod Loader] (forge_server.jar)
>	UCHI    Forge{11.14.3.1543} [Minecraft Forge] (forge_server.jar)
>	UCHE    cfm{3.5} [�9MrCrayfish's Furniture Mod] (MrCrayfishFurnitureModv3.5-dev(1.8).jar)
>	Loaded coremods (and transformers):
>	Profiler Position: N/A (disabled)
>	Is Modded: Definitely; Server brand changed to 'fml,forge'
>	Type: Dedicated Server (map_server.txt)
