### ISSUE TITLE
5.4.1 Doesn't work on a server

### ISSUE THREAD

**Issue by OstenTV** [MrCrayfish/MrCrayfishFurnitureMod#261]
You get an Internal Server Error when trying to join a server with 5.4.1
![image](https://user-images.githubusercontent.com/29460073/43360292-8985a462-92b3-11e8-99d0-ca971e116f6d.png)
![image](https://user-images.githubusercontent.com/29460073/43360283-771fbae2-92b3-11e8-982e-25eb1395409e.png)

**Comment by Teslapirate** [comment]
Some further details, as I am encountering this issue as well. here is the serverside error:

[23:57:29] [Server thread/ERROR] [net.minecraft.server.MinecraftServer]: Encountered an unexpected exception
java.lang.NoClassDefFoundError: net/minecraft/client/resources/I18n
        at com.mrcrayfish.furniture.handler.PlayerEvents.onPlayerLogin(PlayerEvents.java:52) ~[PlayerEvents.class:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1401_PlayerEvents_onPlayerLogin_PlayerLoggedInEvent.invoke(.dynamic) ~[?:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) ~[EventBus.class:?]
        at net.minecraftforge.fml.common.FMLCommonHandler.firePlayerLoggedIn(FMLCommonHandler.java:574) ~[FMLCommonHandler.class:?]
        at net.minecraft.server.management.PlayerList.initializeConnectionToPlayer(PlayerList.java:218) ~[pl.class:?]
...

Please let me know if additional details are required. Thanks!
