### ISSUE TITLE
Crash upon start. 1.12.2 - 5.5.0

### ISSUE THREAD

**Issue by wop0911** [MrCrayfish/MrCrayfishFurnitureMod#274]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  SpongeCoremod (spongeforge-1.12.2-2705-7.1.0-BETA-3361.jar)
Contact their authors BEFORE contacting forge

// Why is it breaking :(

Time: 8/13/18 11:35 AM
Description: Exception in server tick loop

net.minecraftforge.fml.common.LoaderException: cfm Failed load class: com.mrcrayfish.furniture.MrCrayfishFurnitureMod
	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:533)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:218)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:196)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.redirect$onPost$zza000(LoadController.java:560)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:593)
	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:97)
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:332)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:125)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: com.mrcrayfish.furniture.MrCrayfishFurnitureMod
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at net.minecraftforge.fml.common.ModClassLoader.loadClass(ModClassLoader.java:75)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:528)
	... 32 more
Caused by: java.lang.NullPointerException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 38 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:533)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:218)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:196)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.redirect$onPost$zza000(LoadController.java:560)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:593)

-- Sponge PhaseTracker --
Details:
	Phase Stack: [Empty stack]
Stacktrace:
	at net.minecraft.server.MinecraftServer.handler$onCrashReport$zjj000(MinecraftServer.java:3973)
	at net.minecraft.server.MinecraftServer.func_71230_b(MinecraftServer.java:889)
	at net.minecraft.server.dedicated.DedicatedServer.func_71230_b(DedicatedServer.java:370)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:558)
	at java.lang.Thread.run(Thread.java:748)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Linux (amd64) version 4.9.33-mod-std-ipv6-64
	Java Version: 1.8.0_131, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3049255320 bytes (2907 MB) / 6442450944 bytes (6144 MB) up to 8589934592 bytes (8192 MB)
	JVM Flags: 13 total; -Xms6G -Xmx8G -XX:+UseG1GC -XX:+UnlockExperimentalVMOptions -XX:MaxGCPauseMillis=100 -XX:+DisableExplicitGC -XX:TargetSurvivorRatio=90 -XX:G1NewSizePercent=50 -XX:G1MaxNewSizePercent=80 -XX:InitiatingHeapOccupancyPercent=10 -XX:G1MixedGCLiveThresholdPercent=50 -XX:+AggressiveOpts -XX:+AlwaysPreTouch
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.4.2705 44 mods loaded, 44 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                      | Version                     | Source                                       | Signature                                |
	|:----- |:----------------------- |:--------------------------- |:-------------------------------------------- |:---------------------------------------- |
	| UC    | minecraft               | 1.12.2                      | minecraft.jar                                | None                                     |
	| UC    | mcp                     | 9.42                        | minecraft.jar                                | None                                     |
	| UC    | FML                     | 8.0.99.99                   | pixelmonadventure.jar                        | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UC    | forge                   | 14.23.4.2705                | pixelmonadventure.jar                        | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UC    | spongeapi               | 7.1.0-SNAPSHOT-7105dfc      | spongeforge-1.12.2-2705-7.1.0-BETA-3361.jar  | None                                     |
	| UC    | sponge                  | 1.12.2-2705-7.1.0-BETA-3361 | spongeforge-1.12.2-2705-7.1.0-BETA-3361.jar  | 6729a677746f8cf63ef31881f913ed15d431b7f0 |
	| UC    | nuvotifier              | 2.3.5                       | serious-nuvotifier-universal-API7-2.3.5.jar  | None                                     |
	| UC    | aurionsvotelistener     | 1.9                         | AurionsVoteListener-1.0.9.jar                | None                                     |
	| UE    | cfm                     | 5.5.0                       | cfm-5.5.0-mc1.12.2.jar                       | None                                     |
	| U     | customnpcs              | 1.12                        | CustomNPCs_1.12.2(09jul18).jar               | None                                     |
	| U     | dynmap                  | 2.6-beta-1-3                | Dynmap-2.6-beta-1-forge-1.12.jar             | None                                     |
	| U     | economylite             | 2.14.3                      | EconomyLite-7.1.0-2.14.3.jar                 | None                                     |
	| U     | enjin-minecraft-plugin  | 3.4.3-sponge7               | EMPSponge7.jar                               | None                                     |
	| U     | entity-particles        | 2.0.5                       | entity-particles-2.0.5-v7.jar                | None                                     |
	| U     | griefprevention         | 4.3.0                       | griefprevention-1.12.2-4.3.0.646.jar         | None                                     |
	| U     | holograms               | 2.3                         | holograms-2.3.jar                            | None                                     |
	| U     | pixelmon                | 6.3.4                       | Pixelmon-1.12.2-6.3.4-universal.jar          | None                                     |
	| U     | hypermodbanner          | 3.3.0                       | HyperModBanner-1.12.2-3.3.0.jar              | None                                     |
	| U     | ironbackpacks           | 1.12.2-3.0.8-12             | IronBackpacks-1.12.2-3.0.8-12.jar            | None                                     |
	| U     | luckperms               | 4.2.60                      | LuckPerms-Sponge-4.2.60.jar                  | None                                     |
	| U     | nucleus                 | 1.5.1-S7.0                  | Nucleus-1.5.1-S7.0-MC1.12.2-plugin.jar       | None                                     |
	| U     | magibridge              | 2.4.2                       | MagiBridge-API7-2.4.2.jar                    | None                                     |
	| U     | moesmagic               | 2.1.0                       | MoesMagic-1.12.2-2.1.0-universal.jar         | None                                     |
	| U     | multichat               | 1.5                         | multichat-1.5.jar                            | None                                     |
	| U     | nbtedit                 | 1.11.2-2.0.2                | NBTEdit-1.12-2.0.2.jar                       | None                                     |
	| U     | particlesaddon          | 1.1.3                       | particlesaddon-1.1.3.jar                     | None                                     |
	| U     | phantompixelscollection | 1.0.0                       | PhantomPixelsCollection-1.0.0.jar            | None                                     |
	| U     | pixelannouncer          | 1.1.0                       | PixelAnnouncer-1.12.2-1.1.0.jar              | None                                     |
	| U     | pixelextras             | 2.3.9                       | PixelExtras-1.12.2-2.3.9-universal.jar       | None                                     |
	| U     | pixelhunt               | 1.1.1-MC1.12.2-F2705-S7.1.0 | PixelHunt-1.1.1-MC1.12.2-F2705-S7.1.0.jar    | None                                     |
	| U     | pixelmoneconomybridge   | 2.0.1                       | PixelmonEconomyBridge-1.12.2-2.0.1.jar       | None                                     |
	| U     | pixelshout              | 1.2.0                       | PixelShout-1.12.2-1.2.0-universal.jar        | None                                     |
	| U     | pokestop                | 2.0.2                       | PokeStops_1.12.2-2.0.2.jar                   | None                                     |
	| U     | safeplace               | 2.3.0                       | SafePlace-1.12.2-2.4.0.jar                   | None                                     |
	| U     | serverlistplus          | 3.4.8                       | ServerListPlus-3.4.8-Universal.jar           | None                                     |
	| U     | teslacore               | 1.0.1                       | TeslaPowered-s7.0-v1.0.1.jar                 | None                                     |
	| U     | teslacrate              | 2.0.1-legacy                | TeslaCrate-s7.0-t1.0.1-v2.0.1-legacy.jar     | None                                     |
	| U     | teslalibs               | 1.0.1                       | TeslaPowered-s7.0-v1.0.1.jar                 | None                                     |
	| U     | trainercommands         | 2.4.1                       | TrainerCommands-1.12.2-2.4.1-universal.jar   | None                                     |
	| U     | valentines              | 2.0                         | Valentines_2018_1.12.2-2.0.0.jar             | None                                     |
	| U     | variedcommodities       | 1.12.2                      | VariedCommodities_1.12.2(15may18.jar         | None                                     |
	| U     | wondertrade             | 4.5.0                       | WonderTrade-1.12.2-4.5.3b-universal.jar      | None                                     |
	| U     | worldedit               | 6.1.9-SNAPSHOT              | worldedit-forge-mc1.12.1-6.1.9-3770-dist.jar | None                                     |
	| U     | xppokedex               | 0.7                         | xPPokedex-0.7-MC1.12.2-F2611-S7.1.0.jar      | None                                     |

	Loaded coremods (and transformers): 
SpongeCoremod (spongeforge-1.12.2-2705-7.1.0-BETA-3361.jar)
  org.spongepowered.common.launch.transformer.SpongeSuperclassTransformer
	Profiler Position: N/A (disabled)
	Is Modded: Definitely; Server brand changed to 'fml,forge,sponge'
	Type: Dedicated Server (map_server.txt)

**Comment by MrCrayfish** [comment]
Updated to 5.5.1
