### ISSUE TITLE
Furniture Crashing after enter the world

### ISSUE THREAD

**Issue by ronaldobueno81** [MrCrayfish/MrCrayfishFurnitureMod#286]
---- Minecraft Crash Report ----
// You're mean.

Time: 8/19/18 8:52 PM
Description: Exception ticking world

java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.remove(Unknown Source)
	at net.minecraft.world.gen.ChunkProviderServer.func_73156_b(ChunkProviderServer.java:262)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:207)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at java.util.HashMap$HashIterator.remove(Unknown Source)
	at net.minecraft.world.gen.ChunkProviderServer.func_73156_b(ChunkProviderServer.java:262)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:207)

-- Affected level --
Details:
	Level name: Novo mundo
	All players: 0 total; []
	Chunk stats: ServerChunkCache: 622 Drop: 367
	Level seed: 336143031863978585
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 3;minecraft:bedrock,3*minecraft:stone,52*minecraft:sandstone;2;
	Level spawn location: World: (-532,4,-1178), Chunk: (at 12,0,6 in -34,-74; contains blocks -544,0,-1184 to -529,255,-1169), Region: (-2,-3; contains chunks -64,-96 to -33,-65, blocks -1024,0,-1536 to -513,255,-1025)
	Level time: 271 game time, 271 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 158326 (now: false), thunder time: 121322 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (x86) version 10.0
	Java Version: 1.8.0_181, Oracle Corporation
	Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
	Memory: 247318904 bytes (235 MB) / 471343104 bytes (449 MB) up to 1035206656 bytes (987 MB)
	JVM Flags: 7 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx512M -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M -Xmx1000m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.4.2757 5 mods loaded, 5 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID        | Version      | Source                        | Signature                                |
	|:--------- |:--------- |:------------ |:----------------------------- |:---------------------------------------- |
	| UCHIJAAAA | minecraft | 1.12.2       | minecraft.jar                 | None                                     |
	| UCHIJAAAA | mcp       | 9.42         | minecraft.jar                 | None                                     |
	| UCHIJAAAA | FML       | 8.0.99.99    | forge-1.12.2-14.23.4.2757.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge     | 14.23.4.2757 | forge-1.12.2-14.23.4.2757.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | cfm       | 5.5.1        | furniture-5.5.1-1.12.2.jar    | None                                     |

	Loaded coremods (and transformers): 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 0 / 8; []
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

My Minecraft version:
1.12.2

**Comment by MrCrayfish** [comment]
Closing since I won't be maintaining 1.12.2 anymore.
