### ISSUE TITLE
game crashes when staring a world plz fix it

### ISSUE THREAD

**Issue by juicyboxyoutubee** [MrCrayfish/MrCrayfishFurnitureMod#302]
**Describe the bug**

**Crash report**
If applicable, put a link here to your crash report. MrCrayfish suggests you upload your report to https://pastebin.com/ and then put the link to the paste here.

**To Reproduce**
If applicable, the steps to reproduce the behavior:

**Screenshots**

Please complete the following information:
- Minecraft Version:
- Mod Version:

**Comment by juicyboxyoutubee** [comment]
---- Minecraft Crash Report ----
// On the bright side, I bought you a teddy bear!

Time: 8/26/18 5:17 AM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at net.minecraft.world.World.getSkyColorBody(World.java:1481)
	at net.minecraft.world.WorldProvider.getSkyColor(WorldProvider.java:410)
	at net.minecraft.world.World.func_72833_a(World.java:1472)
	at net.minecraft.client.renderer.EntityRenderer.func_78466_h(EntityRenderer.java:1721)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1273)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1259)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1062)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1117)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.world.World.getSkyColorBody(World.java:1481)
	at net.minecraft.world.WorldProvider.getSkyColor(WorldProvider.java:410)
	at net.minecraft.world.World.func_72833_a(World.java:1472)
	at net.minecraft.client.renderer.EntityRenderer.func_78466_h(EntityRenderer.java:1721)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1273)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1259)

-- Affected level --
Details:
	Level name: MpServer
	All players: 0 total; []
	Chunk stats: MultiplayerChunkCache: 0, 0
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (8,64,8), Chunk: (at 8,4,8 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 0 game time, 0 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 0 total; []
	Retry entities: 0 total; []
	Server brand: ~~ERROR~~ NullPointerException: null
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:420)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2748)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:426)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 8.1 (x86) version 6.3
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
	Memory: 328119432 bytes (312 MB) / 901779456 bytes (860 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.42 Powered by Forge 14.23.1.2555 6 mods loaded, 6 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID                | Version      | Source                        | Signature                                |
	|:--------- |:----------------- |:------------ |:----------------------------- |:---------------------------------------- |
	| UCHIJAAAA | minecraft         | 1.12.2       | minecraft.jar                 | None                                     |
	| UCHIJAAAA | mcp               | 9.42         | minecraft.jar                 | None                                     |
	| UCHIJAAAA | FML               | 8.0.99.99    | forge-1.12.2-14.23.1.2555.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge             | 14.23.1.2555 | forge-1.12.2-14.23.1.2555.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | mercurius_updater | 1.0          | MercuriusUpdater-1.12.2.jar   | None                                     |
	| UCHIJAAAA | cfm               | 5.7.0        | cfm-5.7.0-mc1.12.2.jar        | None                                     |

	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'Intel' Version: '4.3.0 - Build 10.18.10.3960' Renderer: 'Intel(R) HD Graphics 4400'
	Launched Version: 1.12.2-forge1.12.2-14.23.1.2555
	LWJGL: 2.9.4
	OpenGL: Intel(R) HD Graphics 4400 GL version 4.3.0 - Build 10.18.10.3960, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (Canada)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i7-4500U CPU @ 1.80GHz

**Comment by JacksonPlayz** [comment]
Stop sending the same crash report. You have to wait and be patient.

**Comment by JacksonPlayz** [comment]
Also, fill out the information. Without that information, Cray won't be able to do anything,

**Comment by juicyboxyoutubee** [comment]
ok then

**Comment by juicyboxyoutubee** [comment]
ok

**Comment by juicyboxyoutubee** [comment]
i am

**Comment by juicyboxyoutubee** [comment]
iam mad

**Comment by juicyboxyoutubee** [comment]
iam ANGRYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY

**Comment by juicyboxyoutubee** [comment]
DO YOU GET IT IAM

**Comment by juicyboxyoutubee** [comment]
ANGRYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY

**Comment by JacksonPlayz** [comment]
He won't ever fix this if you act like this. You didn't fill out the information you were supposed to so he can't fix the issue.

**Comment by QuantumStatement** [comment]
Can't see any traces of Furniture mod in crash report stacktrace

**Comment by JacksonPlayz** [comment]
At the bottom they have the furniture mod installed. Cray already looked at the crash and said it has to do with the mirrors.
