### ISSUE TITLE
Server crash with ThermalExpansion

### ISSUE THREAD

**Issue by vadimyer** [MrCrayfish/MrCrayfishFurnitureMod#32]
I placed a pulverizer and a dishwasher on the left side, got this crash:

```
---- Minecraft Crash Report ----
// I blame Dinnerbone.

Time: 1/28/16 6:07 PM
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
    at cofh.thermalexpansion.util.Utils.isAccessibleOutput(Utils.java:140)
    at cofh.thermalexpansion.block.TileInventory.transferItem(TileInventory.java:171)
    at cofh.thermalexpansion.block.machine.TilePulverizer.transferOutput(TilePulverizer.java:203)
    at cofh.thermalexpansion.block.machine.TileMachineBase.func_145845_h(TileMachineBase.java:122)
    at net.minecraft.world.World.func_72939_s(World.java:2513)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:669)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:954)
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669)
    at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
    at cofh.thermalexpansion.util.Utils.isAccessibleOutput(Utils.java:140)
    at cofh.thermalexpansion.block.TileInventory.transferItem(TileInventory.java:171)
    at cofh.thermalexpansion.block.machine.TilePulverizer.transferOutput(TilePulverizer.java:203)
    at cofh.thermalexpansion.block.machine.TileMachineBase.func_145845_h(TileMachineBase.java:122)

-- Block entity being ticked --
Details:
    Name: thermalexpansion.Pulverizer // cofh.thermalexpansion.block.machine.TilePulverizer
    Block type: ID #861 (tile.thermalexpansion.machine // cofh.thermalexpansion.block.machine.BlockMachine)
    Block data value: 1 / 0x1 / 0b0001
    Block location: World: (841,71,8761), Chunk: (at 9,4,9 in 52,547; contains blocks 832,0,8752 to 847,255,8767), Region: (1,17; contains chunks 32,544 to 63,575, blocks 512,0,8704 to 1023,255,9215)
    Actual block type: ID #861 (tile.thermalexpansion.machine // cofh.thermalexpansion.block.machine.BlockMachine)
    Actual block data value: 1 / 0x1 / 0b0001
Stacktrace:
    at net.minecraft.world.World.func_72939_s(World.java:2513)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:669)
```

Upgraded TE to the latest version... No help at all. After testing all items from mod, figured out that's happening only with dishwasher, washing machine and microwave.

3.4.8 for 1.7.10.

**Comment by Swagbot79** [comment]
Nothing to do with CFM just thermal expansion problems - I think.

**Comment by sudo-apt-get-install** [comment]
This is a thermal expansion error please remove this and report it to https://github.com/CoFH/Feedback/issues

**Comment by vadimyer** [comment]
The only problem is that I've already reported it to them, **before posting here**:
https://github.com/CoFH/Feedback/issues/1020
