### ISSUE TITLE
Crash caused by Rendering Block Entity - Furniture Mod 5.13.0

### ISSUE THREAD

**Issue by fandomaniac** [MrCrayfish/MrCrayfishFurnitureMod#327]
**Description:** Crash from Rendering Block Entity. This is only crashing the Minecraft client software, not the server. Also, it occurred when I was driving a vehicle (mini bike) from the Vehicle mod.

java.lang.NullPointerException: Rendering Block Entity
	at java.util.concurrent.ConcurrentHashMap.get(Unknown Source)
	at java.util.concurrent.ConcurrentHashMap.containsKey(Unknown Source)
	at com.mrcrayfish.furniture.render.tileentity.MirrorRenderer.render(MirrorRenderer.java:57)
	at com.mrcrayfish.furniture.render.tileentity.MirrorRenderer.func_192841_a(MirrorRenderer.java:29)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_192854_a(TileEntityRendererDispatcher.java:155)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_180546_a(TileEntityRendererDispatcher.java:130)
	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:705)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1347)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1259)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1062)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1118)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Full Crash report:**
https://pastebin.com/C0wUUhwe

- Minecraft Version: Forge 1.12.2-14.23.5.2768
- Furniture Mod Version: 5.13.0
- Vehicle Mod Version: 0.21.0

**Comment by fandomaniac** [comment]
It happened again. I was climbing up a ladder when it happened. I wasn't right next to a mirror, but a mirror was in the same chunk. Here's the crash report: https://pastebin.com/55mZ39QY 

The client crashed. The server didn't crash, but here's the server log message recording my client crash:
08.10 20:38:34 [Disconnect] User fandomaniac has disconnected, reason: Internal Exception: io.netty.channel.unix.Errors$NativeIoException: syscall:read(..) failed: Connection reset by peer

**Comment by SanjivanM** [comment]
I've seen this, when you place an IndustrialCraft2 block (I used a pump), then place an electric fence around the pump, leaving no gap between them.  In Survival, run/ walk into the fence.  The game crashes, the crash log has something along the lines of the "Rendering Block Entity", I'll try and post a crash log if needed.
