### ISSUE TITLE
Crafting doesn't work

### ISSUE THREAD

**Issue by V10lator** [MrCrayfish/MrCrayfishFurnitureMod#333]
**Describe the bug**
If i try any recipe nothing happens.

**Screenshots**
![2018-10-22_16 19 27](https://user-images.githubusercontent.com/1312422/47297813-7841c180-d616-11e8-85f8-b8d8a9380967.png)

Please complete the following information:
- Minecraft Version: 1.12.2 
- Mod Version: 5.15.0

**Comment by V10lator** [comment]
Found something in the logs:

[20:18:36] [Server thread/ERROR] [FML]: Parsing error loading recipe cfm:curtains_open
com.google.gson.JsonParseException: Missing data for item 'cfm:curtains_open'
        at net.minecraftforge.common.crafting.CraftingHelper.getItemStack(CraftingHelper.java:215) ~[CraftingHelper.class:?]
        at net.minecraftforge.common.crafting.CraftingHelper.lambda$init$14(CraftingHelper.java:516) ~[CraftingHelper.class:?]
        at net.minecraftforge.common.crafting.CraftingHelper.getRecipe(CraftingHelper.java:409) ~[CraftingHelper.class:?]
        at net.minecraftforge.common.crafting.CraftingHelper.lambda$loadRecipes$22(CraftingHelper.java:711) ~[CraftingHelper.class:?]
        at net.minecraftforge.common.crafting.CraftingHelper.findFiles(CraftingHelper.java:822) ~[CraftingHelper.class:?]
        at net.minecraftforge.common.crafting.CraftingHelper.loadRecipes(CraftingHelper.java:668) ~[CraftingHelper.class:?]
        at java.util.ArrayList.forEach(ArrayList.java:1257) [?:1.8.0_181]
        at net.minecraftforge.common.crafting.CraftingHelper.loadRecipes(CraftingHelper.java:620) [CraftingHelper.class:?]
        at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:742) [Loader.class:?]
        at net.minecraftforge.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:108) [FMLServerHandler.class:?]
        at net.minecraftforge.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:338) [FMLCommonHandler.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:219) [nz.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
