### ISSUE TITLE
washmachine & funnel Crash Server

### ISSUE THREAD

**Issue by Jecvay** [MrCrayfish/MrCrayfishFurnitureMod#34]
When I put a funnel under the washmachine, both the server and the client crash.

after restarting the server, any player who go to that place make the server & client crash again.

**Comment by ShadowCoder69** [comment]
I don't think anybody can do anything withoud a crash report/fml log

**Comment by MrCrayfish** [comment]
Crash log and I assume this is 1.7.10

**Comment by Jecvay** [comment]
I am sorry the log has been cleaned by the server.
the Crash-report:

```
---- Minecraft Crash Report ----
// Ooh. Shiny.

Time: 2/20/16 10:56 PM
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
	at net.minecraft.tileentity.TileEntityHopper.func_152102_a(TileEntityHopper.java:411)
	at net.minecraft.tileentity.TileEntityHopper.func_145883_k(TileEntityHopper.java:324)
	at net.minecraft.tileentity.TileEntityHopper.func_145887_i(TileEntityHopper.java:246)
	at net.minecraft.tileentity.TileEntityHopper.func_145845_h(TileEntityHopper.java:231)
	at net.minecraft.world.World.func_72939_s(World.java:2487)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:664)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:943)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:430)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658)
	at java.lang.Thread.run(Unknown Source)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.tileentity.TileEntityHopper.func_152102_a(TileEntityHopper.java:411)
	at net.minecraft.tileentity.TileEntityHopper.func_145883_k(TileEntityHopper.java:324)
	at net.minecraft.tileentity.TileEntityHopper.func_145887_i(TileEntityHopper.java:246)
	at net.minecraft.tileentity.TileEntityHopper.func_145845_h(TileEntityHopper.java:231)

-- Block entity being ticked --
Details:
	Name: Hopper // net.minecraft.tileentity.TileEntityHopper
	Block type: ID #154 (tile.hopper // net.minecraft.block.BlockHopper)
	Block data value: 5 / 0x5 / 0b0101
	Block location: World: (1001,67,-91), Chunk: (at 9,4,5 in 62,-6; contains blocks 992,0,-96 to 1007,255,-81), Region: (1,-1; contains chunks 32,-32 to 63,-1, blocks 512,0,-512 to 1023,255,-1)
	Actual block type: ID #154 (tile.hopper // net.minecraft.block.BlockHopper)
	Actual block data value: 5 / 0x5 / 0b0101
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:2487)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:664)

-- Affected level --
Details:
	Level name: world
	All players: 27 total; [EntityPlayerMP['ILoveyou_|c'/1656335, l='world', x=-216.50, y=78.00, z=-20.50](ILoveyou_|c at -216.5,78.0,-20.5), EntityPlayerMP['ILoveyou_|c'/1677596, l='world', x=-216.50, y=78.00, z=-20.50](ILoveyou_|c at -216.5,78.0,-20.5), EntityPlayerMP['ILoveyou_|c'/1706078, l='world', x=-216.50, y=78.00, z=-20.50](ILoveyou_|c at -216.5,78.0,-20.5), EntityPlayerMP['婉琳'/52713091, l='world', x=-210.50, y=88.00, z=-26.50](婉琳 at -210.5,88.0,-26.5), EntityPlayerMP['婉琳'/52767135, l='world', x=-210.50, y=88.00, z=-26.50](婉琳 at -210.5,88.0,-26.5), EntityPlayerMP['婉琳'/52850931, l='world', x=-210.50, y=88.00, z=-26.50](婉琳 at -210.5,88.0,-26.5), EntityPlayerMP['婉琳'/52874976, l='world', x=-210.50, y=88.00, z=-26.50](婉琳 at -210.5,88.0,-26.5), EntityPlayerMP['婉琳'/52900380, l='world', x=-210.50, y=88.00, z=-26.50](婉琳 at -210.5,88.0,-26.5), EntityPlayerMP['婉琳'/53014757, l='world', x=-210.50, y=88.00, z=-26.50](婉琳 at -210.5,88.0,-26.5), EntityPlayerMP['婉琳'/53072467, l='world', x=-210.50, y=88.00, z=-26.50](婉琳 at -210.5,88.0,-26.5), EntityPlayerMP['婉琳'/53131566, l='world', x=-210.50, y=88.00, z=-26.50](婉琳 at -210.5,88.0,-26.5), EntityPlayerMP['婉琳'/53255001, l='world', x=-210.50, y=88.00, z=-26.50](婉琳 at -210.5,88.0,-26.5), EntityPlayerMP['mmwll'/76808545, l='world', x=-214.50, y=84.00, z=-32.50](mmwll at -214.5,84.0,-32.5), EntityPlayerMP['mmwll'/76917483, l='world', x=-214.50, y=84.00, z=-32.50](mmwll at -214.5,84.0,-32.5), EntityPlayerMP['mmwll'/76961846, l='world', x=-214.50, y=84.00, z=-32.50](mmwll at -214.5,84.0,-32.5), EntityPlayerMP['Mi9'/89428767, l='world', x=-220.50, y=78.00, z=-39.50](Mi9 at -220.5,78.0,-39.5), EntityPlayerMP['AxinGG'/42435857, l='world', x=580.29, y=81.92, z=-366.47](AxinGG at 580.2917324996756,81.92159999847412,-366.4746613195749), EntityPlayerMP['Xue_Ji'/72685976, l='world', x=1002.81, y=67.30, z=-89.06](Xue_Ji at 1002.8051881020045,67.30000001192093,-89.06491076158441), EntityPlayerMP['Cooler'/105234287, l='world', x=-27.05, y=71.42, z=119.99](Cooler at -27.050891805265405,71.41730646421648,119.98568903389379), EntityPlayerMP['mpz'/103263721, l='world', x=-256.69, y=53.80, z=135.07](mpz at -256.6878487151116,53.80000001192093,135.07499998807907), EntityPlayerMP['Aitman'/121005112, l='world', x=55.50, y=71.85, z=-39.67](Aitman at 55.498211422581214,71.85361577137643,-39.66698094429746), EntityPlayerMP['Luffy'/121938789, l='world', x=852.66, y=63.00, z=-366.50](Luffy at 852.6595354537186,63.0,-366.50396561172994), EntityPlayerMP['Jecvay'/120419231, l='world', x=71.00, y=81.00, z=-29.67](Jecvay at 71.00369000010056,81.0,-29.665326431277244), EntityPlayerMP['liu1517'/11064519, l='world', x=-255.33, y=53.50, z=133.21](liu1517 at -255.32867025460644,53.5,133.21045293498472), EntityPlayerMP['Akey'/129665257, l='world', x=426.67, y=66.10, z=654.12](Akey at 426.67124769314665,66.10408037809304,654.1238882633721), EntityPlayerMP['douyacai'/67394013, l='world', x=-211.81, y=78.00, z=-29.41](douyacai at -211.80877678208645,78.0,-29.413654462039965), EntityPlayerMP['Nation'/115289998, l='world', x=583.69, y=63.00, z=-365.48](Nation at 583.6935875892384,63.0,-365.4757318541587)]
	Chunk stats: ServerChunkCache: 2237 Drop: 0
	Level seed: -6387754376697098933
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (-212,78,-30), Chunk: (at 12,4,2 in -14,-2; contains blocks -224,0,-32 to -209,255,-17), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 10973417 game time, 11788481 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 57936 (now: false), thunder time: 72542 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:943)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:430)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 290521160 bytes (277 MB) / 2440036352 bytes (2327 MB) up to 5726797824 bytes (5461 MB)
	JVM Flags: 2 total; -Xms2G -Xmx6G
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP v9.05 FML v7.10.114.1388 Minecraft Forge 10.13.3.1403 23 mods loaded, 23 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	FML{7.10.114.1388} [Forge Mod Loader] (cauldron-1.7.10-2.1403.1.54-server.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Forge{10.13.3.1403} [Minecraft Forge] (cauldron-1.7.10-2.1403.1.54-server.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	bambootransformer{1.0.0} [BambooTransformer] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	cwm{3.0} [Catoon Weapons Mod] ([1.7.2~1.7.10]卡通武器——Cartoon Weapons[心殇汉化]-V3.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	animalbikes{1.7.10} [Animal Bikes] ([动物单车]AnimalBikes_1.7.10(1).jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	cfm{3.4.7} [?9MrCrayfish's Furniture Mod] ([家具]MrCrayfishFurnitureModv3.4.7(1.7.10)-CN.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	BiblioCraft{1.9.2} [BiblioCraft] ([展示mod]BiblioCraft[v1.9.2][MC1.7.10].jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	MoCreatures{6.3.0} [DrZhark's Mo'Creatures Mod] ([更多生物]DrZharks MoCreatures Mod v6.3.0.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	IronChest{6.0.62.742} [Iron Chest] ([更多箱子]Iron-Chests-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Backpack{2.0.1} [Backpack] ([更多背包]backpack-2.0.1-1.7.x.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	CarpentersBlocks{3.3.7} [Carpenter's Blocks] ([木匠方块]carpenter's Blocks v3.3.7 - MC 1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	mod_ecru_MapleTree{1.1.30j} [MapleTree] ([枫树mod][1.7.10]MapleTree Forge v1.1.30j.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	lovemod{0.1} [Love Mod] ([求婚戒指][汉化]LoveMod-0.1.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	openfm{0.1.0.29} [OpenFM] ([调频]OpenFM-1.7.10-0.1.0-29.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	mod_LATL{1.9} [Lamps and Traffic lights] ([路灯]LampsAndTrafficLights-1.1-Minecraft_1.7.2汉化.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	FoodCraft{1.2.0} [FoodCraft(FoodCraft)] ([食物工艺]FoodCraft-15.8.25-1.2.0-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	mod_WMobility{0.1} [WMobility: Grand Craft Auto] (WMobility-0.1-Minecraft_1.7.10) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	hearts{1.0} [Hearts] (【1.7.10】生命水晶MOD.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	cosmeticWings{1.7.10-0.4.2.14} [Cosmetic Wings] (【1.7.10】自定义翅膀MOD.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	chisel{2.3.7.34} [Chisel 2] (【凿子2】Chisel2-2.3.7.34.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	BambooMod{Minecraft1.7.10 var2.6.8.3} [BambooMod] (【和风】Bamboo-2.6.8.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	CustomSpawner{3.3.0} [DrZhark's CustomSpawner] (【更多生物】CustomMobSpawner 3.3.0.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 17 / 50; [EntityPlayerMP['AxinGG'/42435857, l='world', x=580.29, y=81.92, z=-366.47](AxinGG at 580.2917324996756,81.92159999847412,-366.4746613195749), EntityPlayerMP['Xue_Ji'/72685976, l='world', x=1002.81, y=67.30, z=-89.06](Xue_Ji at 1002.8051881020045,67.30000001192093,-89.06491076158441), EntityPlayerMP['Cooler'/105234287, l='world', x=-27.05, y=71.42, z=119.99](Cooler at -27.050891805265405,71.41730646421648,119.98568903389379), EntityPlayerMP['mpz'/103263721, l='world', x=-256.69, y=53.80, z=135.07](mpz at -256.6878487151116,53.80000001192093,135.07499998807907), EntityPlayerMP['Aitman'/121005112, l='world', x=55.50, y=71.85, z=-39.67](Aitman at 55.498211422581214,71.85361577137643,-39.66698094429746), EntityPlayerMP['Luffy'/121938789, l='world', x=852.66, y=63.00, z=-366.50](Luffy at 852.6595354537186,63.0,-366.50396561172994), EntityPlayerMP['Jecvay'/120419231, l='world', x=71.00, y=81.00, z=-29.67](Jecvay at 71.00369000010056,81.0,-29.665326431277244), EntityPlayerMP['LiLi'/123539432, l='DIM-1', x=-271.33, y=77.00, z=131.20](LiLi at -271.3283456068647,77.0,131.19631145642137), EntityPlayerMP['zhanghao'/104849673, l='zy2', x=-400.01, y=9.00, z=610.56](zhanghao at -400.0092109321349,9.0,610.5605913400618), EntityPlayerMP['liu1517'/11064519, l='world', x=-255.33, y=53.50, z=133.21](liu1517 at -255.32867025460644,53.5,133.21045293498472), EntityPlayerMP['Erich'/50600280, l='zy2', x=-14.59, y=50.00, z=199.90](Erich at -14.587993093185354,50.0,199.89570877262852), EntityPlayerMP['Akey'/129665257, l='world', x=426.67, y=66.10, z=654.12](Akey at 426.67124769314665,66.10408037809304,654.1238882633721), EntityPlayerMP['Rimper'/69267805, l='zy2', x=909.23, y=11.00, z=-262.17](Rimper at 909.2255019710309,11.0,-262.1723823927632), EntityPlayerMP['douyacai'/67394013, l='world', x=-211.81, y=78.00, z=-29.41](douyacai at -211.80877678208645,78.0,-29.413654462039965), EntityPlayerMP['xiazicheng'/99446411, l='zy2', x=906.23, y=11.00, z=-262.54](xiazicheng at 906.2304840969636,11.0,-262.53711985662164), EntityPlayerMP['MC_YNM'/81478231, l='zy2', x=-84.64, y=14.00, z=427.15](MC_YNM at -84.63797683430063,14.0,427.15086610682226), EntityPlayerMP['Nation'/115289998, l='world', x=583.69, y=63.00, z=-365.48](Nation at 583.6935875892384,63.0,-365.4757318541587)]
	Is Modded: Definitely; Server brand changed to 'cauldron,craftbukkit,mcpc,fml,forge'
	Type: Dedicated Server (map_server.txt)
```

**Comment by synthetic65535** [comment]
I have the same crash. How to reproduce:
1. Place a washing machine.
2. Place a hopper facing into washing machine.
3. Put any armor into hopper.
4. Profit. Server will crash.

Here is my crash-report: https://pastebin.com/3JhzjdfA

**Comment by synthetic65535** [comment]
I might be wrong, but... Where is function [getAccessibleSlotsFromSide](https://github.com/vmarchaud/Alkazia/blob/master/1.7.10/Client/src/minecraft/net/minecraft/tileentity/TileEntityHopper.java#L345) in [TileEntityWashingMachine](https://github.com/MrCrayfish/MrCrayfishFurnitureMod/blob/5f983dc8cf8fcf3f1535e7b15589ea665c664953/1.11.2/src/main/java/com/mrcrayfish/furniture/tileentity/TileEntityWashingMachine.java)?

**Comment by MrCrayfish** [comment]
I don't really support 1.7.10 anymore. It's too much time for myself to manage multiple versions of the mod. All I can do really is push the source for the 1.7.10 version and you can just fork it.

**Comment by benjamin-kirkbride** [comment]
@MrCrayfish Sorry to necro, but would it be possible to get the 1.7.10 source?
