### ISSUE TITLE
Shower Server Crash on last 1.10.2

### ISSUE THREAD

**Issue by Loxoz** [MrCrayfish/MrCrayfishFurnitureMod#404]
**Describe the bug**
Shower server crash, you've already fixed this issue but not for Minecraft 1.10.2

**Crash report**
```
Description: Ticking block entity

java.lang.NoSuchMethodError: net.minecraft.entity.player.InventoryPlayer.func_70440_f(I)Lnet/minecraft/item/ItemStack;
	at com.mrcrayfish.furniture.tileentity.TileEntityShowerHead.func_73660_a(TileEntityShowerHead.java:64)
	at net.minecraft.world.World.func_72939_s(World.java:1804)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:620)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:748)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.mrcrayfish.furniture.tileentity.TileEntityShowerHead.func_73660_a(TileEntityShowerHead.java:64)

-- Block entity being ticked --
Details:
	Name: cfmShowerHead // com.mrcrayfish.furniture.tileentity.TileEntityShowerHead
	Block type: ID #830 (tile.shower_head_on // com.mrcrayfish.furniture.blocks.BlockShowerHeadOn)
	Block data value: 1 / 0x1 / 0b0001
	Block location: World: (-1105,57,-1240), Chunk: (at 15,3,8 in -70,-78; contains blocks -1120,0,-1248 to -1105,255,-1233), Region: (-3,-3; contains chunks -96,-96 to -65,-65, blocks -1536,0,-1536 to -1025,255,-1025)
	Actual block type: ID #830 (tile.shower_head_on // com.mrcrayfish.furniture.blocks.BlockShowerHeadOn)
	Actual block data value: 1 / 0x1 / 0b0001
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1804)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:620)
```

**To Reproduce**
1. Place a shower
2. Put a Shower Head
3. Turn ON the Shower Head
4. Go into the shower
-> Server crash

- Minecraft Version: 1.10.2
- Mod Version: cfm-4.1.2-mc1.10.2 (latest on curse & official website)

**Comment by MrCrayfish** [comment]
I don't maintain 1.10.2 anymore.
