### ISSUE TITLE
mirror issue

### ISSUE THREAD

**Issue by noy98** [MrCrayfish/MrCrayfishFurnitureMod#448]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  CorePlugin (SmoothFont.jar)
Contact their authors BEFORE contacting forge

// Who set us up the TNT?

Time: 8/11/19 7:04 PM
Description: Rendering Block Entity

java.lang.IllegalArgumentException: Cannot get property PropertyDirection{name=facing, clazz=class net.minecraft.util.EnumFacing, values=[north, south, west, east]} as it does not exist in BlockStateContainer{block=minecraft:air, properties=[]}
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177229_b(BlockStateContainer.java:209)
	at com.mrcrayfish.furniture.tileentity.TileEntityMirror.getMirror(TileEntityMirror.java:20)
	at com.mrcrayfish.furniture.render.tileentity.MirrorRenderer.render(MirrorRenderer.java:59)
	at com.mrcrayfish.furniture.render.tileentity.MirrorRenderer.func_192841_a(MirrorRenderer.java:29)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_192854_a(TileEntityRendererDispatcher.java:198)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_180546_a(TileEntityRendererDispatcher.java:154)
	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:1031)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1800)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1613)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1384)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by Kexerval** [comment]
Also having this same bug. 
https://paste.dimdev.org/sikunenawe.mccrash
