### ISSUE TITLE
1.14.4 Client crash with: CreativeScreenEvents.updateTagButtons

### ISSUE THREAD

**Issue by Wissi** [MrCrayfish/MrCrayfishFurnitureMod#462]
When in creative pressing "E" to access inventory it crashes client with:
```
java.lang.NullPointerException: Unexpected error
	at com.mrcrayfish.furniture.client.event.CreativeScreenEvents.updateTagButtons(CreativeScreenEvents.java:220) ~[?:7.0.0-pre9-1.14.4] {}
	at com.mrcrayfish.furniture.client.event.CreativeScreenEvents.onScreenInit(CreativeScreenEvents.java:98) ~[?:7.0.0-pre9-1.14.4] {}
	at net.minecraftforge.eventbus.ASMEventHandler_681_CreativeScreenEvents_onScreenInit_Post.invoke(.dynamic) ~[?:?] {}
```
**Crash report**
Full crash report [here](https://gist.github.com/Wissi/767ea6895470a9eac95af42e08df11e7).

**To Reproduce**
If applicable, the steps to reproduce the behavior:
When in creative pressing "E" to access inventory it crashes client

**Screenshots**

Please complete the following information:
- Minecraft Version: 1.14.4
- Mod Version: furniture-7.0.0-pre9-1.14.4.jar
- Forge version: -28.1.10

**Comment by DvlDddy** [comment]
Same issue here.

**Comment by krometh** [comment]
Same.. Any fix???

**Comment by BadHarry00** [comment]
I have the same Problem, but i have update my Forge 28.1.19.  The error comes, if i open the Inventor Tab with standard hotkey 'e'. i have only forge, cfm-7.0.0-pre9-mc1.14.4 and u_team_core-1.14.4-2.7.0.129 mods installed.

In the Server latest.log:
`[24Sep2019 12:13:15.696] [Forge Version Check/INFO] [net.minecraftforge.fml.VersionChecker/]: [cfm] Starting version check at https://raw.githubusercontent.com/MrCrayfish/MrCrayfishFurnitureMod/master/update.json
[24Sep2019 12:13:15.704] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer/]: Loading properties
[24Sep2019 12:13:15.721] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer/]: Default game type: SURVIVAL
[24Sep2019 12:13:15.722] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer/]: Generating keypair
[24Sep2019 12:13:16.885] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer/]: Starting Minecraft server on *:26565
[24Sep2019 12:13:17.262] [Server thread/INFO] [net.minecraft.network.NetworkSystem/]: Using epoll channel type
[24Sep2019 12:13:18.249] [Forge Version Check/WARN] [net.minecraftforge.fml.VersionChecker/]: Failed to process update information
java.io.FileNotFoundException: https://raw.githubusercontent.com/MrCrayfish/MrCrayfishFurnitureMod/master/update.json
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_171]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_171]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_171]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_171]
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1944) ~[?:1.8.0_171]
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1939) ~[?:1.8.0_171]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_171]
	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1938) ~[?:1.8.0_171]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1508) ~[?:1.8.0_171]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492) ~[?:1.8.0_171]
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:263) ~[?:1.8.0_171]
	at net.minecraftforge.fml.VersionChecker$1.openUrlStream(VersionChecker.java:189) ~[?:?]
	at net.minecraftforge.fml.VersionChecker$1.process(VersionChecker.java:206) ~[?:?]
	at java.lang.Iterable.forEach(Iterable.java:75) [?:1.8.0_171]
	at net.minecraftforge.fml.VersionChecker$1.run(VersionChecker.java:157) [?:?]
Caused by: java.io.FileNotFoundException: https://raw.githubusercontent.com/MrCrayfish/MrCrayfishFurnitureMod/master/update.json
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1890) ~[?:1.8.0_171]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492) ~[?:1.8.0_171]
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480) ~[?:1.8.0_171]
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:347) ~[?:1.8.0_171]
	at net.minecraftforge.fml.VersionChecker$1.openUrlStream(VersionChecker.java:173) ~[?:?]
	... 3 more`

i Tried to open the Link 'https://raw.githubusercontent.com/MrCrayfish/MrCrayfishFurnitureMod/master/update.json' but i get the Error 404.  
Maybe the problem ?

[crash-2019-09-24_14.13.34-client.txt](https://github.com/MrCrayfish/MrCrayfishFurnitureMod/files/3647169/crash-2019-09-24_14.13.34-client.txt)
