### ISSUE TITLE
[1.14.4] crashing server every time when grill put down

### ISSUE THREAD

**Issue by Domas268** [MrCrayfish/MrCrayfishFurnitureMod#486]
**Describe the bug**

**Crash report**
If applicable, put a link here to your crash report. MrCrayfish suggests you upload your report to https://pastebin.com/ and then put the link to the paste here.

**To Reproduce**
If applicable, the steps to reproduce the behavior:

**Screenshots**

Please complete the following information:
- Minecraft Version:
- Mod Version:

**Comment by LorenzoPapi** [comment]
Write your mod version and Minecraft version. Post your log and crash report. Write steps to reproduce the bug.

**Comment by MrCrayfish** [comment]
Good job at filling out the information! 👍

**Comment by Alethalen** [comment]
Having the same issue, have forge 28.1.90/1.14.4 server and have 1.14.4 client  it has an issue with flipping the steaks? because when u place or reload server and then click on placed grill it stops the server i have pasted below exact error
[23Nov2019 11:57:13.817] [Server thread/ERROR] [net.minecraft.server.MinecraftServer/]: Encountered an unexpected exception
java.lang.NoSuchFieldError: flipping
	at com.mrcrayfish.furniture.tileentity.GrillTileEntity.<init>(GrillTileEntity.java:53) ~[?:7.0.0-pre12-1.14.4]
	at com.mrcrayfish.furniture.block.GrillBlock.createTileEntity(GrillBlock.java:128) ~[?:7.0.0-pre12-1.14.4]
	at net.minecraftforge.common.extensions.IForgeBlockState.createTileEntity(IForgeBlockState.java:149) ~[?:?]
	at net.minecraft.world.chunk.Chunk.func_177436_a(Chunk.java:288) ~[?:?]
	at net.minecraft.world.World.func_180501_a(World.java:192) ~[?:?]
	at net.minecraft.item.BlockItem.func_195941_b(BlockItem.java:146) ~[?:?]
	at net.minecraft.item.BlockItem.func_195942_a(BlockItem.java:54) ~[?:?]
	at net.minecraft.item.BlockItem.func_195939_a(BlockItem.java:39) ~[?:?]
	at net.minecraftforge.common.ForgeHooks.onPlaceItemIntoWorld(ForgeHooks.java:607) ~[?:?]
	at net.minecraft.item.ItemStack.func_196084_a(ItemStack.java:162) ~[?:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_219441_a(PlayerInteractionManager.java:328) ~[?:?]
	at net.minecraft.network.play.ServerPlayNetHandler.func_184337_a(ServerPlayNetHandler.java:847) ~[?:?]
	at net.minecraft.network.play.client.CPlayerTryUseItemOnBlockPacket.func_148833_a(SourceFile:36) ~[?:?]
	at net.minecraft.network.play.client.CPlayerTryUseItemOnBlockPacket.func_148833_a(SourceFile:10) ~[?:?]
	at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21) ~[?:?]
	at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) ~[?:?]
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:699) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:693) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(SourceFile:103) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:678) ~[?:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:626) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_231]
