### ISSUE TITLE
1.14.4 Grill Crashes Server : Flipping Error

### ISSUE THREAD

**Issue by Alethalen** [MrCrayfish/MrCrayfishFurnitureMod#488]
**Describe the bug**
When placing the grill of any colour down the server instantly closes with an error.
Upon reloading the world server, the grill is there but as soon as u click on it or place another down the same issue happens.
Forge Version: 28.1.90
Minecraft: 1.14.4
Mods
SecurityKraft 1.18.x
CFM-pre12

NOTE:
**Crash report**
[23Nov2019 11:57:13.817] [Server thread/ERROR] [net.minecraft.server.MinecraftServer/]: Encountered an unexpected exception
java.lang.NoSuchFieldError: flipping
at com.mrcrayfish.furniture.tileentity.GrillTileEntity.(GrillTileEntity.java:53) ~[?:7.0.0-pre12-1.14.4]
at com.mrcrayfish.furniture.block.GrillBlock.createTileEntity(GrillBlock.java:128) ~[?:7.0.0-pre12-1.14.4]
at net.minecraftforge.common.extensions.IForgeBlockState.createTileEntity(IForgeBlockState.java:149) ~[?:?]
at net.minecraft.world.chunk.Chunk.func_177436_a(Chunk.java:288) ~[?:?]
at net.minecraft.world.World.func_180501_a(World.java:192) ~[?:?]
at net.minecraft.item.BlockItem.func_195941_b(BlockItem.java:146) ~[?:?]
at net.minecraft.item.BlockItem.func_195942_a(BlockItem.java:54) ~[?:?]
at net.minecraft.item.BlockItem.func_195939_a(BlockItem.java:39) ~[?:?]
at net.minecraftforge.common.ForgeHooks.onPlaceItemIntoWorld(ForgeHooks.java:607) ~[?:?]
at net.minecraft.item.ItemStack.func_196084_a(ItemStack.java:162) ~[?:?]
at net.minecraft.server.management.PlayerInteractionManager.func_219441_a(PlayerInteractionManager.java:328) ~[?:?]
at net.minecraft.network.play.ServerPlayNetHandler.func_184337_a(ServerPlayNetHandler.java:847) ~[?:?]
at net.minecraft.network.play.client.CPlayerTryUseItemOnBlockPacket.func_148833_a(SourceFile:36) ~[?:?]
at net.minecraft.network.play.client.CPlayerTryUseItemOnBlockPacket.func_148833_a(SourceFile:10) ~[?:?]
at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21) ~[?:?]
at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?]
at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) ~[?:?]
at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?]
at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) ~[?:?]
at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:699) ~[?:?]
at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:693) ~[?:?]
at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(SourceFile:103) ~[?:?]
at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:678) ~[?:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:626) [?:?]
at java.lang.Thread.run(Unknown Source) [?:1.8.0_231]
**To Reproduce**
If applicable, the steps to reproduce the behavior:
1. Go to 'Inventory'
2. Click on 'Magenta Grill'
3. Place on the Ground or click an existing one

**Comment by LorenzoPapi** [comment]
I know what the issue is. At **"com.mrcrayfish.furniture.tileentity.GrillTileEntity"** on line 53 **there is the flipping field** , but it's **ClientOnly** , so the server doesn't look for it and it crashes.

**Comment by Alethalen** [comment]
> I know what the issue is. At **"com.mrcrayfish.furniture.tileentity.GrillTileEntity"** on line 53 **there is the flipping field** , but it's **ClientOnly** , so the server doesn't look for it and it crashes.
I dont beleive the .GrillTileEntity.class is in my .jar file

**Comment by LorenzoPapi** [comment]
Really? Where have you downloaded the mod from? Try downloading the mod from this site:https://www.curseforge.com/minecraft/mc-mods/mrcrayfish-furniture-mod
Or try the official MrCrayfish website:https://mrcrayfish.com/mods?id=cfm 
And the class is **GrillTileEntity**, without the dot.

**Comment by Alethalen** [comment]
i got it direct from crayfish.com ive downloaded both copies and none of them contain the cooler.class or grill.class

**Comment by Alethalen** [comment]
funny, i just checked this morning and they have been added ill test and let you know

**Comment by Alethalen** [comment]
https://pastebin.com/qm4EJhVS
No luck.. think it needs some work before an actual release for servers.
When playing Single Player it works fine.
