### ISSUE TITLE
Breaking the cookie jar crashes the game

### ISSUE THREAD

**Issue by Hyrules** [MrCrayfish/MrCrayfishFurnitureMod#50]
If I add a cookie jar and try to remove it the game crashes : 

Here is the error log :  

---- Minecraft Crash Report ----

WARNING: coremods are present:
  ThaumcraftLoader (Thaumcraft-1.8.9-5.2.4.jar)
  MalisisCorePlugin (malisiscore-1.8.9-2.1.3.jar)
Contact their authors BEFORE contacting forge

// Ouch. That hurt :(

Time: 4/9/16 5:06 PM
Description: Rendering Block Entity

java.lang.IllegalArgumentException: Cannot get property PropertyInteger{name=cookie_count, clazz=class java.lang.Integer, values=[0, 1, 2, 3, 4, 5, 6]} as it does not exist in BlockState{block=minecraft:air, properties=[]}
	at net.minecraft.block.state.BlockState$StateImplementation.func_177229_b(BlockState.java:137)
	at com.mrcrayfish.furniture.blocks.BlockCookieJar.func_176201_c(BlockCookieJar.java:156)
	at com.mrcrayfish.furniture.render.tileentity.CookieRenderer.func_180535_a(CookieRenderer.java:55)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_178469_a(TileEntityRendererDispatcher.java:136)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_180546_a(TileEntityRendererDispatcher.java:114)
	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:900)
	at shadersmod.client.ShadersRender.renderShadowMap(ShadersRender.java:343)
	at shadersmod.client.Shaders.beginRender(Shaders.java:3637)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1522)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1328)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1051)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.block.state.BlockState$StateImplementation.func_177229_b(BlockState.java:137)
	at com.mrcrayfish.furniture.blocks.BlockCookieJar.func_176201_c(BlockCookieJar.java:156)
	at com.mrcrayfish.furniture.render.tileentity.CookieRenderer.func_180535_a(CookieRenderer.java:55)

-- Block Entity Details --
Details:
	Name: cfmCookieJar // com.mrcrayfish.furniture.tileentity.TileEntityCookieJar
	Block type: ID #255 (tile.cookie_jar // com.mrcrayfish.furniture.blocks.BlockCookieJar)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (663,87,16), Chunk: (at 7,5,0 in 41,1; contains blocks 656,0,16 to 671,255,31), Region: (1,0; contains chunks 32,0 to 63,31, blocks 512,0,0 to 1023,255,511)
	Actual block type: ID #0 (tile.air // net.minecraft.block.BlockAir)
	Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_178469_a(TileEntityRendererDispatcher.java:136)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_180546_a(TileEntityRendererDispatcher.java:114)
	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:900)
	at shadersmod.client.ShadersRender.renderShadowMap(ShadersRender.java:343)
	at shadersmod.client.Shaders.beginRender(Shaders.java:3637)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1522)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Hyrules82'/161, l='MpServer', x=664.69, y=86.00, z=15.96]]
	Chunk stats: MultiplayerChunkCache: 2601, 2601
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: 212.00,64.00,208.00 - World: (212,64,208), Chunk: (at 4,4,0 in 13,13; contains blocks 208,0,208 to 223,255,223), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 532714 game time, 17770 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: true), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 34 total; [EntitySquid['Squid'/192, l='MpServer', x=643.50, y=45.28, z=-48.53], EntityBat['Bat'/193, l='MpServer', x=617.81, y=36.13, z=71.91], EntityBat['Bat'/217, l='MpServer', x=605.00, y=15.06, z=71.78], EntityBat['Bat'/218, l='MpServer', x=739.28, y=11.28, z=-44.25], EntityBat['Bat'/219, l='MpServer', x=739.63, y=15.25, z=-41.56], EntityBat['Bat'/221, l='MpServer', x=740.00, y=15.38, z=-42.09], EntityBat['Bat'/223, l='MpServer', x=716.09, y=13.81, z=81.63], EntitySquid['Squid'/224, l='MpServer', x=708.97, y=53.84, z=78.97], EntitySheep['Sheep'/162, l='MpServer', x=672.00, y=63.00, z=14.47], EntityLift['Elevator'/163, l='MpServer', x=659.50, y=85.00, z=10.50], EntitySheep['Sheep'/164, l='MpServer', x=650.34, y=63.00, z=15.78], EntitySheep['Sheep'/165, l='MpServer', x=684.91, y=63.00, z=5.63], EntitySheep['Sheep'/166, l='MpServer', x=673.53, y=63.00, z=14.50], EntitySheep['Sheep'/167, l='MpServer', x=660.97, y=65.00, z=31.25], EntitySheep['Sheep'/168, l='MpServer', x=662.31, y=64.00, z=19.44], EntitySheep['Sheep'/169, l='MpServer', x=655.50, y=62.47, z=31.25], EntitySheep['Sheep'/170, l='MpServer', x=652.31, y=69.00, z=-12.94], EntitySquid['Squid'/171, l='MpServer', x=700.84, y=50.91, z=10.91], EntitySquid['Squid'/173, l='MpServer', x=708.41, y=49.31, z=0.41], EntitySquid['Squid'/174, l='MpServer', x=718.09, y=55.59, z=-4.03], EntitySquid['Squid'/175, l='MpServer', x=709.50, y=54.41, z=1.03], EntityBat['Bat'/176, l='MpServer', x=652.19, y=17.31, z=62.53], EntitySquid['Squid'/177, l='MpServer', x=664.72, y=53.88, z=51.59], EntitySquid['Squid'/178, l='MpServer', x=718.25, y=52.91, z=-3.66], EntitySquid['Squid'/179, l='MpServer', x=717.22, y=56.63, z=-7.72], EntitySquid['Squid'/180, l='MpServer', x=710.34, y=52.84, z=-14.50], EntityBat['Bat'/181, l='MpServer', x=613.53, y=20.06, z=-24.47], EntityBat['Bat'/182, l='MpServer', x=636.53, y=15.66, z=-44.16], EntityBat['Bat'/183, l='MpServer', x=633.53, y=16.00, z=-38.41], EntitySquid['Squid'/184, l='MpServer', x=633.81, y=50.34, z=-42.34], EntitySquid['Squid'/185, l='MpServer', x=634.69, y=48.03, z=-44.72], EntityBat['Bat'/186, l='MpServer', x=733.75, y=26.59, z=3.22], EntityPlayerSP['Hyrules82'/161, l='MpServer', x=664.69, y=86.00, z=15.96], EntitySquid['Squid'/190, l='MpServer', x=718.16, y=52.41, z=-13.44]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:404)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2536)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:370)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Windows 10 (amd64) version 10.0
	CPU: 16x Intel(R) Core(TM) i7-5960X CPU @ 3.00GHz
	Java Version: 1.8.0_77, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 4607438008 bytes (4393 MB) / 6429081600 bytes (6131 MB) up to 6429081600 bytes (6131 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M -Xmx6144M -Xms6144M
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.19 Powered by Forge 11.15.1.1847 Optifine OptiFine_1.8.9_HD_U_H5 14 mods loaded, 14 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8.9-11.15.1.1847.jar) 
	UCHIJAAAA	Forge{11.15.1.1847} [Minecraft Forge] (forge-1.8.9-11.15.1.1847.jar) 
	UCHIJAAAA	ArchitectureCraft{1.4.1} [ArchitectureCraft] (ArchitectureCraft-1.4.1-mc1.8.9.jar) 
	UCHIJAAAA	cfm{3.6} [MrCrayfish's Furniture Mod] (cfm-3.6.1-mc1.8.9.jar) 
	UCHIJAAAA	cfmce{1.0.1} [MrCrayfish's Furniture Mod: Community Edition] (cfmce-1.0.1-mc1.8.9.jar) 
	UCHIJAAAA	journeymap{1.8.9-5.1.5} [JourneyMap] (journeymap-1.8.9-5.1.5-unlimited.jar) 
	UCHIJAAAA	malisiscore{1.8.9-2.1.3} [MalisisCore] (malisiscore-1.8.9-2.1.3.jar) 
	UCHIJAAAA	malisisdoors{1.8.9-3.1.3} [MalisisDoors] (malisisdoors-1.8.9-3.1.3.jar) 
	UCHIJAAAA	Baubles{1.1.3.0} [Baubles] (Baubles-1.8.9-1.1.3.0.jar) 
	UCHIJAAAA	Thaumcraft{5.2.4} [Thaumcraft] (Thaumcraft-1.8.9-5.2.4.jar) 
	UCHIJAAAA	thutcore{2.4.6} [ThutCore] (thutcore-1.8.9-2.4.6.jar) 
	UCHIJAAAA	thuttech{2.3.5} [Thut's Tech] (thuttech-2.3.5.jar) 
	UCHIJAAAA	worldedit{6.1.1} [WorldEdit] (worldedit-forge-mc1.8.9-6.1.1.jar) 
	Loaded coremods (and transformers): 
ThaumcraftLoader (Thaumcraft-1.8.9-5.2.4.jar)
  
MalisisCorePlugin (malisiscore-1.8.9-2.1.3.jar)
  net.malisis.core.util.chunkcollision.ChunkCollisionTransformer
  net.malisis.core.util.chunkblock.ChunkBlockTransformer
  net.malisis.core.renderer.transformer.MalisisRendererTransformer
  net.malisis.core.renderer.icon.asm.TextureMapTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 364.51' Renderer: 'GeForce GTX TITAN X/PCIe/SSE2'
	Launched Version: 1.8.9-forge1.8.9-11.15.1.1847
	LWJGL: 2.9.4
	OpenGL: GeForce GTX TITAN X/PCIe/SSE2 GL version 4.5.0 NVIDIA 364.51, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: LIFE 128x (Vers. 81).zip
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 16x Intel(R) Core(TM) i7-5960X CPU @ 3.00GHz
	OptiFine Version: OptiFine_1.8.9_HD_U_H5
	Render Distance Chunks: 25
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: Continuum Preview - 1.8.9 - Preview2.zip
	OpenGlVersion: 4.5.0 NVIDIA 364.51
	OpenGlRenderer: GeForce GTX TITAN X/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 16

**Comment by Hyrules** [comment]
After more investigation, the bug happens only when shaders are activated. I'm using optifine with continuum shaders.

**Comment by MrCrayfish** [comment]
This has been fixed. I should have a patch out very soon!

**Comment by Hyrules** [comment]
Big thanks ! Your mod is a geat addition to the minecraft world. Thanks again.

**Comment by MrCrayfish** [comment]
The latest version 3.6.2 should fix the problem now :)
