### ISSUE TITLE
[1.12.2] HashMap ConcurrentModificationException

### ISSUE THREAD

**Issue by Yuti35** [MrCrayfish/MrCrayfishFurnitureMod#578]
**Describe the bug**
I have a server with 4 mods, I recently add the furniture mod and this bugs happens.
It crash the server, without giving more information.
I tried to remove all the mod and keep only the furniture mod and it's the only one which seems to do that.
It seems to be a ConcurrentModificationException.

**Crash report**
// I just don't know what went wrong :(

Time: 5/30/20 2:35 PM
Description: Exception in server tick loop

java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1445)
	at java.util.HashMap$KeyIterator.next(HashMap.java:1469)
	at net.minecraft.entity.EntityTracker.func_72788_a(EntityTracker.java:290)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:779)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:748)

**To Reproduce**
Unfortunatly, the bug happens randomly, but I can say it come from this mod.

- Minecraft Version: 1.12.2
- Mod Version: 6.3.0

**Comment by StarchierOrb** [comment]
The same to me .
It may cause by exchanging items on computer.
I reported to the catserver dev team and they said it may cause by asynchronous add entity.(mod problem) They fixed this by blocking async event to prevent crash, but the result is computer is broken now.XD

Stacktrace like this:
https://paste.ubuntu.com/p/wHWwwJgr9X/
