### ISSUE TITLE
[1.12.2] GIF downloader crash on Ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by Aeris1One** [MrCrayfish/MrCrayfishFurnitureMod#607]
I'm playing on some server with this mod and I crash every time I go near to a TV or something playing a GIF.

```
[20:05:22] [Image Download Thread/INFO] [STDERR]: [com.mrcrayfish.furniture.client.GifDownloadThread:run:97]: java.net.MalformedURLException: no protocol: TF1
[20:05:22] [Image Download Thread/INFO] [STDERR]: [com.mrcrayfish.furniture.client.GifDownloadThread:run:97]:     at java.net.URL.<init>(URL.java:611)
[20:05:22] [Image Download Thread/INFO] [STDERR]: [com.mrcrayfish.furniture.client.GifDownloadThread:run:97]:     at java.net.URL.<init>(URL.java:508)
[20:05:22] [Image Download Thread/INFO] [STDERR]: [com.mrcrayfish.furniture.client.GifDownloadThread:run:97]:     at java.net.URL.<init>(URL.java:457)
[20:05:22] [Image Download Thread/INFO] [STDERR]: [com.mrcrayfish.furniture.client.GifDownloadThread:run:97]:     at com.mrcrayfish.furniture.client.GifDownloadThread.run(GifDownloadThread.java:70)
```

**Comment by SuperHarmony910** [comment]
@Aeris1One Are you sure if it is a GIF? There are many trustworthy-looking websites that actually don't have GIFs, rather HTML files. Check [here](https://www.youtube.com/watch?v=q-xJZ6aFwXU) for more info!

**Comment by Aeris1One** [comment]
It was a GIF, people using the mod under Windows were not affected by this bug. I had this bug playing on a server and the devs fixed this, idk how.

**Comment by SuperHarmony910** [comment]
It doesn't look like an issue to me in the log, maybe you should close this issue if it has been resolved. :)
