### ISSUE TITLE
[Minecraft Version 1.7.10] When I try to play Minecraft with the furniture mod installed it crashes at stage 6/7 

### ISSUE THREAD

**Issue by CMMANGO** [MrCrayfish/MrCrayfishFurnitureMod#655]
When I try to play Minecraft with the furniture mod installed it crashes at stage 6/7 and I love this mod and it really annoys me that this is happening.

Mod Version 3.4.7 [1.7.10]

Pls fix ASAP

Crash Report:

---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 27/01/21 11:34 PM
Description: Initializing game

java.lang.NullPointerException: Initializing game
	at com.mrcrayfish.furniture.api.RecipeData.toString(RecipeData.java:190)
	at com.mrcrayfish.furniture.api.Recipes.updateDataList(Recipes.java:251)
	at com.mrcrayfish.furniture.MrCrayfishFurnitureMod.loadComplete(MrCrayfishFurnitureMod.java:687)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:742)
	at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:311)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:552)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at com.mrcrayfish.furniture.api.RecipeData.toString(RecipeData.java:190)
	at com.mrcrayfish.furniture.api.Recipes.updateDataList(Recipes.java:251)
	at com.mrcrayfish.furniture.MrCrayfishFurnitureMod.loadComplete(MrCrayfishFurnitureMod.java:687)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:742)
	at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:311)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:552)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2050348392 bytes (1955 MB) / 6576668672 bytes (6272 MB) up to 9663676416 bytes (9216 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx9G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 Optifine OptiFine_1.7.10_HD_U_E7 104 mods loaded, 104 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJ	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJ	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJ	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJ	Aroma1997Core{1.0.2.16} [Aroma1997Core] (Aroma1997Core-1.7.10-1.0.2.16.jar) 
	UCHIJ	CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) 
	UCHIJ	Micdoodlecore{} [Micdoodle8 Core] (minecraft.jar) 
	UCHIJ	PlayerAPI{1.4} [Player API] (minecraft.jar) 
	UCHIJ	TooManyItems{1.7.10} [TooManyItems] (minecraft.jar) 
	UCHIJ	xaerominimap_core{1.7.10-1.0} [XaeroMinimapCore] (minecraft.jar) 
	UCHIJ	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UCHIJ	FoamFixCore{1.0.0-beta1} [FoamFixCore] (minecraft.jar) 
	UCHIJ	sapmanpack{2.5.1} [SanAndreasPs Manager Pack CORE edition] (SanAndreasPs-Manager-Pack-1.7.10.jar) 
	UCHIJ	securitycraft{v1.8.2.2} [SecurityCraft] ([1.7.10]+SecurityCraft+v1.8.2.2.jar) 
	UCHIJ	CoFHCore{1.7.10R3.1.4} [CoFH Core] (CoFHCore-[1.7.10]3.1.4-329.jar) 
	UCHIJ	BuildCraft|Core{7.1.23} [BuildCraft] (buildcraft-7.1.23.jar) 
	UCHIJ	BuildCraft|Energy{7.1.23} [BC Energy] (buildcraft-7.1.23.jar) 
	UCHIJ	ActuallyAdditions{1.7.10-r21} [Actually Additions] (ActuallyAdditions-1.7.10-r21.jar) 
	UCHIJ	ArchitectureCraft{1.7.2} [ArchitectureCraft] (ArchitectureCraft-1.7.2-mc1.7.10.jar) 
	UCHIJ	armourersWorkshop{1.7.10-0.48.5} [Armourer's Workshop] (Armourers-Workshop-1.7.10-0.48.5.jar) 
	UCHIJ	Aroma1997CoreHelper{1.0.2.16} [Aroma1997Core|Helper] (Aroma1997Core-1.7.10-1.0.2.16.jar) 
	UCHIJ	Aroma1997sDimension{1.0} [Aroma1997's Dimensional World] (Aroma1997s-Dimensional-World-1.7.10-1.1.0.1.jar) 
	UCHIJ	iChunUtil{4.0.0} [iChunUtil] (iChunUtil-4.0.0.jar) 
	UCHIJ	BackTools{4.0.0} [BackTools] (Back-Tools-Mod-1.7.10.jar) 
	UCHIJ	backpacks16840{3.5.7} [Backpacks!] (backpacks+1.7.10+-+3.5.7.jar) 
	UCHIJ	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) 
	UCHIJ	betterbuilderswands{0.8.1} [Better Builder's Wands] (BetterBuildersWands-0.8.1-1.7.10r92+aec06c3.jar) 
	UCHIJ	BetterFoliage{2.0.17} [Better Foliage] (BetterFoliage-MC1.7.10-2.0.17.jar) 
	UCHIJ	BiblioCraft{1.11.6} [BiblioCraft] (BiblioCraft[v1.11.6][MC1.7.10].jar) 
	UCHIJ	biggerpacketsplz{1.2} [Bigger Packets, please !] (biggerpacketsplz-upto1.7.10-1.2.jar) 
	UCHIJ	Billund{1.0.0} [CCMODNAME] (Billund-Mod-1.7.10.jar) 
	UCHIJ	BiomesOPlenty{2.1.0} [Biomes O' Plenty] (BiomesOPlenty-1.7.10-2.1.0.1889-universal.jar) 
	UCHIJ	birdsfoods{3.1 - [1.7.10]} [Bird's Foods] (Birds-Foods-Mod-1.7.10.jar) 
	UCHIJ	Botania{r1.8-249} [Botania] (Botania r1.8-249.jar) 
	UCHIJ	BuildCraft|Transport{7.1.23} [BC Transport] (buildcraft-7.1.23.jar) 
	UCHIJ	BuildCraft|Factory{7.1.23} [BC Factory] (buildcraft-7.1.23.jar) 
	UCHIJ	BuildCraft|Silicon{7.1.23} [BC Silicon] (buildcraft-7.1.23.jar) 
	UCHIJ	BuildCraft|Robotics{7.1.23} [BC Robotics] (buildcraft-7.1.23.jar) 
	UCHIJ	BuildCraft|Builders{7.1.23} [BC Builders] (buildcraft-7.1.23.jar) 
	UCHIJ	CarpentersBlocks{3.3.8.2} [Carpenter's Blocks] (Carpenter's+Blocks+v3.3.8.2+-+MC+1.7.10.jar) 
	UCHIJ	carsanddrives{1.0.9.1} [Cars and Drives] (Cars_and_Drives_Mod_V-1.0.9.1.jar) 
	UCHIJ	ChestTransporter{2.0.6} [Chest Transporter] (ChestTransporter-1.7.10-2.0.6.jar) 
	UCHIJ	chunkpregenerator{2.4.1} [Chunk Pregenerator] (Chunk Pregenerator-V1.7.10-2.4.1.jar) 
	UCHIJ	claysoldiers{2.0.0-beta.2} [Clay Soldiers Mod] (Clay-Soldiers-Mod-1.7.10.jar) 
	UCHIJ	CopiousDogs{${mcversion}-${version}} [Copious Dogs] (Copious-Dogs-Mod-by-wolfpupKG52-1.7.10.jar) 
	UCHIJ	craftingtweaks{1.0.88} [Crafting Tweaks] (craftingtweaks-mc1.7.10-1.0.88.jar) 
	UCHIJ	MineTweaker3{3.1.0} [MineTweaker 3] (CraftTweaker-1.7.10-3.1.0-legacy.jar) 
	UCHIJ	CustomMainMenu{1.9.2} [Custom Main Menu] (CustomMainMenu-MC1.7.10-1.9.2.jar) 
	UCHIJ	customnpcs{1.7.10d} [CustomNpcs] (CustomNPCs_1.7.10d(29oct17).jar) 
	UCHIJ	PTRModelLib{1.0.0} [PTRModelLib] (Decocraft-2.4.2_1.7.10.jar) 
	UCHIJ	props{2.4.2} [Decocraft] (Decocraft-2.4.2_1.7.10.jar) 
	UCHIJ	MoCreatures{6.3.1} [DrZhark's Mo'Creatures Mod] (DrZharks MoCreatures Mod v6.3.1.zip) 
	UCHIJ	DynamicLights{1.3.9a} [Dynamic Lights] (Dynamic+Lights-1.3.9a-MC1.7.10.jar) 
	UCHIJ	EnderStorage{1.4.7.37} [EnderStorage] (EnderStorage-1.7.10-1.4.7.37-universal.jar) 
	UCHIJ	fantastic{1.0.0} [Fantastic Fish] (fantastic-1.4.jar) 
	UCHIJ	fastleafdecay{1.3} [Fast Leaf Decay] (FastLeafDecay-Mod-1.7.10.jar) 
	UCHIJ	flansmod{4.10.0} [Flan's Mod] (Flans Mod-1.7.10-4.10.0.jar) 
	UCHIJ	flashlight{ï¿½{version}} [Flashlight Mod] (Flashlight-1.7.10-1.0.jar) 
	UCHIJ	foamfix{@VERSION@} [FoamFix] (FoamFix-1.7.10-universal-1.0.0-beta1.jar) 
	UCHIJ	FoodExpansion{1.0} [Food Expansion] (Food-Expansion-Mod-1.7.10.jar) 
	UCHIJ	IC2{2.2.827-experimental} [IndustrialCraft 2] (industrialcraft-2-2.2.827-experimental.jar) 
	UCHIJ	Forestry{4.2.16.64} [Forestry for Minecraft] (forestry_1.7.10-4.2.16.64.jar) 
	UCHIJ	Mantle{1.7.10-0.3.2.jenkins191} [Mantle] (Mantle-1.7.10-0.3.2b.jar) 
	UCHIJ	ImmersiveEngineering{0.7.7} [Immersive Engineering] (ImmersiveEngineering-0.7.7.jar) 
	UCHIJ	Waila{1.5.10} [Waila] (Waila-1.5.10_1.7.10.jar) 
	UCHIJ	TConstruct{1.7.10-1.8.8.build988} [Tinkers' Construct] (TConstruct-1.7.10-1.8.8.jar) 
	UCHIJ	GalacticraftCore{3.0.12} [Galacticraft Core] (GalacticraftCore-1.7-3.0.12.504.jar) 
	UCHIJ	GalacticraftMars{3.0.12} [Galacticraft Planets] (Galacticraft-Planets-1.7-3.0.12.504.jar) 
	UCHIJ	GalaxySpace{1.2.14 Pre-Final} [GalaxySpace] (GalaxySpace-1.7.10-1.2.14.jar) 
	UCHIJ	hamsterrific{0.2.2} [Hamsterrific] (hamsterrific-0.2.2.jar) 
	UCHIJ	Hats{4.0.1} [Hats] (Hats-4.0.1.jar) 
	UCHIJ	InventoryPets{1.5.2} [Inventory Pets] (inventorypets-1.7.10-1.5.2-universal.jar) 
	UCHIJ	gender{1.0.1} [Gender] (iPixelis-Gender-Mod-1.7.10.jar) 
	UCHIJ	ironbackpacks{1.7.10-1.2.20} [Iron Backpacks] (IronBackpacks-1.7.10-1.2.20.jar) 
	UCHIJ	IronChest{6.0.62.742} [Iron Chest] (ironchest-1.7.10-6.0.62.742-universal.jar) 
	UCHIJ	journeymap{5.1.4p2} [JourneyMap] (journeymap-1.7.10-5.1.4p2-unlimited.jar) 
	UCHIJ	KeepingInventory{2.1} [Keeping Inventory] (KeepingInventory-1.7.10-2.1.jar) 
	UCHIJ	malisiscore{1.7.10-0.14.3} [MalisisCore] (MalisisCore-1.7.10.jar) 
	UCHIJ	malisisdoors{1.7.10-1.13.2} [Malisis' Doors] (MalisisDoors-Mod-1.7.10.jar) 
	UCHIJ	mcheli{1.0.3} [MC Helicopter] (mcheli) 
	UCHIJ	MedicineCraft{V4.0} [MedicineCraft] (MedicineCraft-V4.2-1.7.10.jar) 
	UCHIJ	ForgeMultipart{1.1.2.331} [Forge Multipart] (ForgeMultipart-1.7.10-1.1.2.331-universal.jar) 
	UCHIJ	Mekanism{9.1.1} [Mekanism] (Mekanism-1.7.10-9.1.1.1031.jar) 
	UCHIJ	MinecraftDonalds{v6.0} [MinecraftDonalds] (MinecraftDonaldsMod v6.0.zip) 
	UCHIJ	mobends{0.20.1} [Mo' Bends] (Mo-Bends-Mod-1.7.10.jar) 
	UCHIJ	Morph{0.9.3} [Morph] (Morph-Beta-0.9.3.jar) 
	UCHIE	cfm{3.4.7} [§9MrCrayfish's Furniture Mod] (MrCrayfishFurnitureModv3.4.7(1.7.10).jar) 
	UCHIJ	NetherOres{1.7.10R2.3.1} [Nether Ores] (NetherOres-[1.7.10]2.3.1-22.jar) 
	UCHIJ	notenoughIDs{1.4.3.4} [NotEnoughIDs] (NotEnoughIDs-1.4.3.4.jar) 
	UCHIJ	OreSpawn{1.7.10.20.3} [OreSpawn] (Ore-Spawn-Mod-1.7.10.zip) 
	UCHIJ	starwarsmod{1.3.3} [Parzi's Star Wars Mod] (Parzi's+Star+Wars+Mod+v1.3.3.jar) 
	UCHIJ	placeableitems{2.0.1} [Placeable Items Mod] (placeableitems-2.0.1.jar) 
	UCHIJ	corerm{1.0c} [RikMuld's Core] (RikMuldsCore_1.0c.jar) 
	UCHIJ	secretroomsmod{4.7.1} [The SecretRoomsMod] (Secret-Rooms-Mod-1.7.10.jar) 
	UCHIJ	sit{v1.1} [Sit] (sit-1.7.10-v1.1.jar) 
	UCHIJ	Sync{4.0.1} [Sync] (Sync-Mod-1.7.10.jar) 
	UCHIJ	camping{2.1g} [The Camping Mod 2] (TheCampingMod_2.1g.jar) 
	UCHIJ	kitchen{1.3.23} [The Kitchen Mod] (TheKitchenMod-1.3.23-1.7.2-10.jar) 
	UCHIJ	ctrades{1.3.2} [Custom Trades Mod] (Trades-mc1.7.10-1.3.2.jar) 
	UCHIJ	bspkrsCore{6.15} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.15.jar) 
	UCHIJ	Treecapitator{1.7.10} [Treecapitator] (Tree-Capitator-Mod-1.7.10.jar) 
	UCHIJ	worldedit{6.1.1} [WorldEdit] (worldedit-forge-mc1.7.10-6.1.1-dist.jar) 
	UCHIJ	XaeroMinimap{21.0.0} [Xaero's Minimap] (Xaeros_Minimap_21.0.0_Forge_1.7.10.jar) 
	UCHIJ	McMultipart{1.1.2.331} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.1.2.331-universal.jar) 
	UCHIJ	ForgeMicroblock{1.1.2.331} [Forge Microblocks] (ForgeMultipart-1.7.10-1.1.2.331-universal.jar) 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 461.40' Renderer: 'GeForce GTX 1660 Ti/PCIe/SSE2'
	CoFHCore: -[1.7.10]3.1.4-329
	Mantle Environment: DO NOT REPORT THIS CRASH! Unsupported mods in environment: optifine
	TConstruct Environment: Environment healthy.
	NetherOres: -[1.7.10]2.3.1-22
	Forestry : Warning: You have mods that change the behavior of Minecraft, ForgeModLoader, and/or Minecraft Forge to your client: 
Optifine
These may have caused this error, and may not be supported. Try reproducing the crash WITHOUT these mods, and report it then.
	Armourer's Workshop: 
		Render Type: MODEL_ATTACHMENT
		Texture Render: false
		Baking Queue: 0
		Request Queue: 0
		Texture Painting: true
		Multipass Skin Rendering: true
	Launched Version: 1.7.10-Forge10.13.4.1614-1.7.10
	LWJGL: 2.9.1
	OpenGL: GeForce GTX 1660 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 461.40, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

**Comment by MrCrayfish** [comment]
1.7.10 version discontinued
