### ISSUE TITLE
Game crashes when a doorbell is placed on a trampoline 

### ISSUE THREAD

**Issue by sudo-apt-get-install** [MrCrayfish/MrCrayfishFurnitureMod#68]
`java.lang.IllegalArgumentException: Cannot set property PropertyDirection{name=facing, clazz=class net.minecraft.util.EnumFacing, values=[north, south, west, east]} to down on block cfm:door_bell, it is not an allowed value
	at net.minecraft.block.state.BlockState$StateImplementation.func_177226_a(BlockState.java:160)
	at com.mrcrayfish.furniture.blocks.BlockDoorBell.func_180642_a(BlockDoorBell.java:103)
	at net.minecraft.item.ItemBlock.func_180614_a(ItemBlock.java:55)
	at net.minecraft.item.ItemStack.func_179546_a(ItemStack.java:135)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_178890_a(PlayerControllerMP.java:403)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1491)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2036)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1024)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
`

`-- Head --
Stacktrace:
	at net.minecraft.block.state.BlockState$StateImplementation.func_177226_a(BlockState.java:160)
	at com.mrcrayfish.furniture.blocks.BlockDoorBell.func_180642_a(BlockDoorBell.java:103)
	at net.minecraft.item.ItemBlock.func_180614_a(ItemBlock.java:55)
	at net.minecraft.item.ItemStack.func_179546_a(ItemStack.java:135)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_178890_a(PlayerControllerMP.java:403)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1491)
`

**Comment by MrCrayfish** [comment]
Can you tell me how to replicate this? The behaviour of placing a door bell doesn't allow it to be placed on non-full blocks.

**Comment by sudo-apt-get-install** [comment]
Unreplicatable, only happened once.
