### ISSUE TITLE
I have no idea what this is

### ISSUE THREAD

**Issue by sudo-apt-get-install** [MrCrayfish/MrCrayfishFurnitureMod#69]
`[13:38:59] [Client thread/ERROR] [FML]: Exception loading model for variant cfm:item_log#inventory
java.lang.Exception: Could not load model definition for variant cfm:item_log#inventory
	at net.minecraftforge.client.model.ModelLoader.func_177586_a(ModelLoader.java:211) ~[ModelLoader.class:?]
	at net.minecraftforge.client.model.ModelLoader.loadItems(ModelLoader.java:255) ~[ModelLoader.class:?]
	at net.minecraftforge.client.model.ModelLoader.func_177570_a(ModelLoader.java:112) ~[ModelLoader.class:?]
	at net.minecraft.client.resources.model.ModelManager.func_110549_a(ModelManager.java:28) [bou.class:?]
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110544_b(SimpleReloadableResourceManager.java:130) [bnn.class:?]
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110541_a(SimpleReloadableResourceManager.java:111) [bnn.class:?]
	at net.minecraft.client.Minecraft.func_110436_a(Minecraft.java:732) [ave.class:?]
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:326) [FMLClientHandler.class:?]
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:495) [ave.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:329) [ave.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_77]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_77]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_77]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_77]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.RuntimeException: Encountered an exception when loading model definition of model cfm:blockstates/item_log.json
	at net.minecraft.client.resources.model.ModelBakery.func_177586_a(ModelBakery.java:165) ~[bot.class:?]
	at net.minecraftforge.client.model.ModelLoader.func_177586_a(ModelLoader.java:207) ~[ModelLoader.class:?]
	... 16 more
Caused by: java.io.FileNotFoundException: cfm:blockstates/item_log.json
	at net.minecraft.client.resources.FallbackResourceManager.func_135056_b(FallbackResourceManager.java:93) ~[bnb.class:?]
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_135056_b(SimpleReloadableResourceManager.java:78) ~[bnn.class:?]
	at net.minecraft.client.resources.model.ModelBakery.func_177586_a(ModelBakery.java:143) ~[bot.class:?]
	at net.minecraftforge.client.model.ModelLoader.func_177586_a(ModelLoader.java:207) ~[ModelLoader.class:?]
	... 16 more
[13:38:59] [Client thread/ERROR] [FML]: Model definition for location cfm:plate#normal not found
[13:38:59] [Client thread/ERROR] [FML]: Model definition for location cfm:divingboard_plank#inventory not found
[13:38:59] [Client thread/ERROR] [FML]: Model definition for location cfm:item_log#inventory not found
[13:39:00] [Client thread/ERROR] [TEXTURE ERRORS]: +=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=
[13:39:00] [Client thread/ERROR] [TEXTURE ERRORS]: The following texture errors were found.
[13:39:00] [Client thread/ERROR] [TEXTURE ERRORS]: ==================================================
[13:39:00] [Client thread/ERROR] [TEXTURE ERRORS]:   DOMAIN minecraft
[13:39:00] [Client thread/ERROR] [TEXTURE ERRORS]: --------------------------------------------------
[13:39:00] [Client thread/ERROR] [TEXTURE ERRORS]:   domain minecraft is missing 1 texture
[13:39:00] [Client thread/ERROR] [TEXTURE ERRORS]:     domain minecraft has 3 locations:
[13:39:00] [Client thread/ERROR] [TEXTURE ERRORS]:       unknown resourcepack type net.minecraft.client.resources.DefaultResourcePack : Default
[13:39:00] [Client thread/ERROR] [TEXTURE ERRORS]:       mod cfm resources at censored/mods/cfm-4.0pre1-mc1.8.9.jar
[13:39:00] [Client thread/ERROR] [TEXTURE ERRORS]:       resource pack at path censored/resourcepacks/faithful32pack.zip
[13:39:00] [Client thread/ERROR] [TEXTURE ERRORS]: -------------------------
[13:39:00] [Client thread/ERROR] [TEXTURE ERRORS]:     The missing resources for domain minecraft are:
[13:39:00] [Client thread/ERROR] [TEXTURE ERRORS]:       textures/blocks/blocks/leaves_oak.png
[13:39:00] [Client thread/ERROR] [TEXTURE ERRORS]: -------------------------
[13:39:00] [Client thread/ERROR] [TEXTURE ERRORS]:     No other errors exist for domain minecraft
[13:39:00] [Client thread/ERROR] [TEXTURE ERRORS]: ==================================================
[13:39:00] [Client thread/ERROR] [TEXTURE ERRORS]: ==================================================
[13:39:00] [Client thread/ERROR] [TEXTURE ERRORS]:   DOMAIN cfm
[13:39:00] [Client thread/ERROR] [TEXTURE ERRORS]: --------------------------------------------------
[13:39:00] [Client thread/ERROR] [TEXTURE ERRORS]:   domain cfm is missing 1 texture
[13:39:00] [Client thread/ERROR] [TEXTURE ERRORS]:     domain cfm has 1 location:
[13:39:00] [Client thread/ERROR] [TEXTURE ERRORS]:       mod cfm resources at censored/mods/cfm-4.0pre1-mc1.8.9.jar
[13:39:00] [Client thread/ERROR] [TEXTURE ERRORS]: -------------------------
[13:39:00] [Client thread/ERROR] [TEXTURE ERRORS]:     The missing resources for domain cfm are:
[13:39:00] [Client thread/ERROR] [TEXTURE ERRORS]:       textures/items/itemmoney.png
[13:39:00] [Client thread/ERROR] [TEXTURE ERRORS]: -------------------------
[13:39:00] [Client thread/ERROR] [TEXTURE ERRORS]:     No other errors exist for domain cfm
[13:39:00] [Client thread/ERROR] [TEXTURE ERRORS]: ==================================================
[13:39:00] [Client thread/ERROR] [TEXTURE ERRORS]: +=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=`

**Comment by GravityLens** [comment]
you're lucky, your issue number is #69

**Comment by sudo-apt-get-install** [comment]
Ayyyyy

**Comment by sudo-apt-get-install** [comment]
Fixed
