### ISSUE TITLE
[1.17] java.lang.NoSuchMethodError: 'void com.mrcrayfish.furniture.entity.SeatEntity.remove(boolean)'

### ISSUE THREAD

**Issue by Gander7** [MrCrayfish/MrCrayfishFurnitureMod#692]
Added the mod and a friend immediately crafted and sat in a chair, which was fine, but when she tried to get out of the chair, the server crashed with the following error. Everytime she logged on, it would crash with the error and I thought it might be the event so I went over to destroy the chair but as soon as I came out of the nether portal and the chunks were loaded the server crashed.

```
net.minecraft.ReportedException: Ticking entity
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:886) ~[server-1.17.1-20210706.113038-srg.jar%2325!:?]
	at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:334) ~[server-1.17.1-20210706.113038-srg.jar%2325!:?]
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:818) ~[server-1.17.1-20210706.113038-srg.jar%2325!:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:683) ~[server-1.17.1-20210706.113038-srg.jar%2325!:?]
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:258) ~[server-1.17.1-20210706.113038-srg.jar%2325!:?]
	at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.NoSuchMethodError: 'void com.mrcrayfish.furniture.entity.SeatEntity.remove(boolean)'
	at com.mrcrayfish.furniture.entity.SeatEntity.m_8119_(SeatEntity.java:48) ~[cfn-7.0.0pre23-1.17.1.jar%2323!:7.0.0-pre23-1.17.1]
	at net.minecraft.server.level.ServerLevel.m_8647_(ServerLevel.java:623) ~[server-1.17.1-20210706.113038-srg.jar%2325!:?]
	at net.minecraft.world.level.Level.m_46653_(Level.java:470) ~[server-1.17.1-20210706.113038-srg.jar%2325!:?]
	at net.minecraft.server.level.ServerLevel.m_143264_(ServerLevel.java:384) ~[server-1.17.1-20210706.113038-srg.jar%2325!:?]
	at net.minecraft.world.level.entity.EntityTickList.m_156910_(SourceFile:54) ~[server-1.17.1-20210706.113038-srg.jar%2325!:?]
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:365) ~[server-1.17.1-20210706.113038-srg.jar%2325!:?]
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:882) ~[server-1.17.1-20210706.113038-srg.jar%2325!:?]
	... 5 more
	```

**Comment by MrCrayfish** [comment]
Fixed in https://github.com/MrCrayfish/MrCrayfishFurnitureMod/commit/3152d2ff3c36c92ae32fac59018423061db6bbeb
