### ISSUE TITLE
Game crashed after placing sink, unable to open the same world

### ISSUE THREAD

**Issue by 5h4d0wDr4g0n** [MrCrayfish/MrCrayfishFurnitureMod#719]
Error report as follows, explanation as per title

---- Minecraft Crash Report ----

Time: 1/21/22, 8:20 PM
Description: Exception in server tick loop

java.lang.NoSuchMethodError: 'net.minecraft.nbt.CompoundTag com.mrcrayfish.furniture.tileentity.FluidHandlerSyncedBlockEntity.save(net.minecraft.nbt.CompoundTag)'
	at com.mrcrayfish.furniture.tileentity.FluidHandlerSyncedBlockEntity.m_5995_(FluidHandlerSyncedBlockEntity.java:67) ~[furniture-7.0.0-pre27-1.18.1.jar%2361!/:7.0.0-pre27-1.18.1] {re:classloading}
	at net.minecraft.network.protocol.game.ClientboundLevelChunkPacketData$BlockEntityInfo.m_195691_(ClientboundLevelChunkPacketData.java:153) ~[client-1.18.1-20211210.034407-srg.jar%2372!/:?] {re:mixin,re:classloading,pl:mixin:APP:supplementaries.mixins.json:ChunkHolderMixin,pl:mixin:A}
	at net.minecraft.network.protocol.game.ClientboundLevelChunkPacketData.<init>(ClientboundLevelChunkPacketData.java:44) ~[client-1.18.1-20211210.034407-srg.jar%2372!/:?] {re:classloading}
	at net.minecraft.network.protocol.game.ClientboundLevelChunkWithLightPacket.<init>(ClientboundLevelChunkWithLightPacket.java:24) ~[client-1.18.1-20211210.034407-srg.jar%2372!/:?] {re:classloading}
	at net.minecraft.server.level.ChunkMap.m_183760_(ChunkMap.java:1125) ~[client-1.18.1-20211210.034407-srg.jar%2372!/:?] {re:classloading,re:mixin}
	at net.minecraft.server.level.ChunkMap.m_183754_(ChunkMap.java:785) ~[client-1.18.1-20211210.034407-srg.jar%2372!/:?] {re:classloading,re:mixin}
	at net.minecraft.server.level.ChunkMap.m_140192_(ChunkMap.java:923) ~[client-1.18.1-20211210.034407-srg.jar%2372!/:?] {re:classloading,re:mixin}
	at net.minecraft.server.level.ChunkMap.m_140199_(ChunkMap.java:1045) ~[client-1.18.1-20211210.034407-srg.jar%2372!/:?] {re:classloading,re:mixin}
	at net.minecraft.server.level.ServerChunkCache.m_8463_(ServerChunkCache.java:458) ~[client-1.18.1-20211210.034407-srg.jar%2372!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.level.ServerLevel$EntityCallbacks.m_141985_(ServerLevel.java:1551) ~[client-1.18.1-20211210.034407-srg.jar%2372!/:?] {re:classloading}
	at net.minecraft.server.level.ServerLevel$EntityCallbacks.m_141985_(ServerLevel.java:1534) ~[client-1.18.1-20211210.034407-srg.jar%2372!/:?] {re:classloading}
	at net.minecraft.world.level.entity.PersistentEntitySectionManager.m_157575_(PersistentEntitySectionManager.java:135) ~[client-1.18.1-20211210.034407-srg.jar%2372!/:?] {re:classloading}
	at net.minecraft.world.level.entity.PersistentEntitySectionManager.addEntityWithoutEvent(PersistentEntitySectionManager.java:98) ~[client-1.18.1-20211210.034407-srg.jar%2372!/:?] {re:classloading}
	at net.minecraft.world.level.entity.PersistentEntitySectionManager.addNewEntityWithoutEvent(PersistentEntitySectionManager.java:76) ~[client-1.18.1-20211210.034407-srg.jar%2372!/:?] {re:classloading}
	at net.minecraft.server.level.ServerLevel.m_8853_(ServerLevel.java:827) ~[client-1.18.1-20211210.034407-srg.jar%2372!/:?] {re:classloading,pl:accesstransformer:B,xf:fml:forgeendertech:coremod,re:mixin,pl:accesstransformer:B,xf:fml:forgeendertech:coremod}
	at net.minecraft.server.level.ServerLevel.m_8834_(ServerLevel.java:771) ~[client-1.18.1-20211210.034407-srg.jar%2372!/:?] {re:classloading,pl:accesstransformer:B,xf:fml:forgeendertech:coremod,re:mixin,pl:accesstransformer:B,xf:fml:forgeendertech:coremod}
	at net.minecraft.server.players.PlayerList.m_11261_(PlayerList.java:190) ~[client-1.18.1-20211210.034407-srg.jar%2372!/:?] {re:classloading}
	at net.minecraft.server.network.ServerLoginPacketListenerImpl.m_143699_(ServerLoginPacketListenerImpl.java:138) ~[client-1.18.1-20211210.034407-srg.jar%2372!/:?] {re:classloading}
	at net.minecraft.server.network.ServerLoginPacketListenerImpl.m_10055_(ServerLoginPacketListenerImpl.java:125) ~[client-1.18.1-20211210.034407-srg.jar%2372!/:?] {re:classloading}
	at net.minecraft.server.network.ServerLoginPacketListenerImpl.m_10050_(ServerLoginPacketListenerImpl.java:69) ~[client-1.18.1-20211210.034407-srg.jar%2372!/:?] {re:classloading}
	at net.minecraft.network.Connection.m_129483_(Connection.java:229) ~[client-1.18.1-20211210.034407-srg.jar%2372!/:?] {re:mixin,re:classloading}
	at net.minecraft.server.network.ServerConnectionListener.m_9721_(ServerConnectionListener.java:142) ~[client-1.18.1-20211210.034407-srg.jar%2372!/:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:882) ~[client-1.18.1-20211210.034407-srg.jar%2372!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:808) ~[client-1.18.1-20211210.034407-srg.jar%2372!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:86) ~[client-1.18.1-20211210.034407-srg.jar%2372!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:668) ~[client-1.18.1-20211210.034407-srg.jar%2372!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:258) ~[client-1.18.1-20211210.034407-srg.jar%2372!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:833) [?:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.18.1
	Minecraft Version ID: 1.18.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 1235218640 bytes (1177 MiB) / 4127195136 bytes (3936 MiB) up to 5737807872 bytes (5472 MiB)
	CPUs: 8
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 1500X Quad-Core Processor          
	Identifier: AuthenticAMD Family 23 Model 1 Stepping 1
	Microarchitecture: Zen
	Frequency (GHz): 3.49
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: Radeon (TM) RX 470 Graphics
	Graphics card #0 vendor: Advanced Micro Devices, Inc. (0x1002)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x67df
	Graphics card #0 versionInfo: DriverVersion=30.0.14011.3017
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.40
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.40
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 24505.44
	Virtual memory used (MB): 21694.24
	Swap memory total (MB): 8192.00
	Swap memory used (MB): 426.58
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx5472m -Xms256m
	Server Running: true
	Player Count: 1 / 8; [ServerPlayer['5h4d0wDr4g0n'/166, l='ServerLevel[New World]', x=-295.26, y=71.00, z=358.71]]
	Data Packs: vanilla, mod:mcwbridges, mod:farmersdelight, mod:mcwdoors, mod:cfm (incompatible), mod:chunkanimator (incompatible), mod:mcwtrpdoors, mod:mcwfences, mod:jei (incompatible), mod:mcwwindows, mod:cloth_config (incompatible), mod:skinlayers3d (incompatible), mod:forge, mod:bambooeverything (incompatible), mod:supplementaries (incompatible), mod:forgeendertech, mod:adchimneys, mod:mcwpaintings, mod:selene (incompatible), mod:mcwlights, mod:drinkbeer (incompatible), mod:configured (incompatible)
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'; Server brand changed to 'forge'
	ModLauncher: 9.1.0+9.1.0+main.6690ee51
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		 mixin PLUGINSERVICE 
		 eventbus PLUGINSERVICE 
		 object_holder_definalize PLUGINSERVICE 
		 runtime_enum_extender PLUGINSERVICE 
		 capability_token_subclass PLUGINSERVICE 
		 accesstransformer PLUGINSERVICE 
		 runtimedistcleaner PLUGINSERVICE 
		 mixin TRANSFORMATIONSERVICE 
		 fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		javafml@null
	Mod List: 
		client-1.18.1-20211210.034407-srg.jar             |Minecraft                     |minecraft                     |1.18.1              |DONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		mcw-bridges-2.0.1-mc1.18.1.jar                    |Macaw's Bridges               |mcwbridges                    |2.0.1               |DONE      |Manifest: NOSIGNATURE
		FarmersDelight-1.18.1-1.0.3.jar                   |Farmer's Delight              |farmersdelight                |1.18.1-1.0.3        |DONE      |Manifest: NOSIGNATURE
		configured-1.5.1-1.18.1.jar                       |Configured                    |configured                    |1.5.1               |DONE      |Manifest: NOSIGNATURE
		mcw-doors-1.0.5-mc1.18.1.jar                      |Macaw's Doors                 |mcwdoors                      |1.0.5               |DONE      |Manifest: NOSIGNATURE
		furniture-7.0.0-pre27-1.18.1.jar                  |MrCrayfish's Furniture Mod    |cfm                           |7.0.0-pre27         |DONE      |Manifest: NOSIGNATURE
		ChunkAnimator-1.18-1.3.3.jar                      |Chunk Animator                |chunkanimator                 |1.18-1.3.3          |DONE      |Manifest: NOSIGNATURE
		mcw-trapdoors-1.0.4-mc1.18.1.jar                  |Macaw's Trapdoors             |mcwtrpdoors                   |1.0.4               |DONE      |Manifest: NOSIGNATURE
		mcw-fences-1.0.2-mc1.18.1.jar                     |Macaw's Fences and Walls      |mcwfences                     |1.0.2               |DONE      |Manifest: NOSIGNATURE
		jei-1.18.1-9.2.1.69.jar                           |Just Enough Items             |jei                           |9.2.1.69            |DONE      |Manifest: NOSIGNATURE
		mcw-windows-2.0.2-mc1.18.1.jar                    |Macaw's Windows               |mcwwindows                    |2.0.2               |DONE      |Manifest: NOSIGNATURE
		cloth-config-6.1.48-forge.jar                     |Cloth Config v4 API           |cloth_config                  |6.1.48              |DONE      |Manifest: NOSIGNATURE
		3dSkinLayers-forge-mc1.18-1.3.1.jar               |3dSkinLayers                  |skinlayers3d                  |1.3.1               |DONE      |Manifest: NOSIGNATURE
		forge-1.18.1-39.0.55-universal.jar                |Forge                         |forge                         |39.0.55             |DONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		bambooeverything-1.2.4-build.10+mc1.18.1.jar      |Bamboo Everything             |bambooeverything              |1.2.4-build.10+mc1.1|DONE      |Manifest: NOSIGNATURE
		supplementaries-1.18.1-1.1.9.jar                  |Supplementaries               |supplementaries               |1.1.9               |DONE      |Manifest: NOSIGNATURE
		ForgeEndertech-1.18.1-8.0.0.0-build.0040.jar      |ForgeEndertech                |forgeendertech                |08.0.0.0            |DONE      |Manifest: NOSIGNATURE
		AdChimneys-1.18.1-7.0.0.1-build.0043.jar          |Advanced Chimneys             |adchimneys                    |07.0.0.1            |DONE      |Manifest: NOSIGNATURE
		mcw-paintings-1.0.2-mc1.18.1.jar                  |Macaw's Paintings             |mcwpaintings                  |1.0.2               |DONE      |Manifest: NOSIGNATURE
		selene-1.18-1.12.0.jar                            |Selene                        |selene                        |1.18-1.12.0         |DONE      |Manifest: NOSIGNATURE
		mcw-lights-1.0.2-mc1.18.1.jar                     |Macaw's Lights and Lamps      |mcwlights                     |1.0.2               |DONE      |Manifest: NOSIGNATURE
		drinkbeer-v2.3.5 for 1.18.1.jar                   |Drink Beer                    |drinkbeer                     |2.3.5               |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: 558c25e1-5fc7-41f7-aac4-e15787e0ee8f
	FML: 39.0
	Forge: net.minecraftforge:39.0.55

**Comment by MrCrayfish** [comment]
Update to pre28
