### ISSUE TITLE
[1.19.3] NoClassDefFoundError

### ISSUE THREAD

**Issue by Zemogiter** [MrCrayfish/MrCrayfishFurnitureMod#785]
**Describe the bug**
After loading screen, the game fails to display main menu with this:
```
[18sty2023 18:44:53.835] [modloading-worker-0/ERROR] [net.minecraftforge.fml.javafmlmod.FMLModContainer/LOADING]: Failed to create mod instance. ModID: cfm, class com.mrcrayfish.furniture.FurnitureMod
java.lang.NoClassDefFoundError: net/minecraft/data/tags/BlockTagsProvider
	at java.lang.Class.getDeclaredConstructors0(Native Method) ~[?:?]
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:3373) ~[?:?]
	at java.lang.Class.getConstructor0(Class.java:3578) ~[?:?]
	at java.lang.Class.getDeclaredConstructor(Class.java:2754) ~[?:?]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:68) ~[javafmllanguage-1.19.3-44.1.5.jar%23318!/:?]
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:121) ~[fmlcore-1.19.3-44.1.5.jar%23317!/:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
Caused by: java.lang.ClassNotFoundException: net.minecraft.data.tags.BlockTagsProvider
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:141) ~[securejarhandler-2.1.6.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	... 13 more
```
**Crash report**
[latest.log](https://github.com/MrCrayfish/MrCrayfishFurnitureMod/files/10449179/latest.log)
[crash-2023-01-18_18.44.58-fml.txt](https://github.com/MrCrayfish/MrCrayfishFurnitureMod/files/10449180/crash-2023-01-18_18.44.58-fml.txt)

Please complete the following information:
- Minecraft Version: 1.19.3
- Mod Version: cfm-7.0.0-pre34-1.19

**Comment by MrCrayfish** [comment]
1.19.2 mods mostly don't work on 1.19.3
